tyler-technologies-oss/forge

src/lib/select/select/_selector.scss

The placeholder text is now aligned properly in all densities when no label text is set:
Fixes #128

fix(select): fixed placeholder text alignment when no label is set

---

src/lib/theme/_theme-values.scss
src/stories/src/core/theme-color-grid.tsx
src/stories/src/guides/theming.stories.mdx

The `border-color` style will now use a hex color without an opacity to ensure that the color is properly rendered without the background color affecting the result and potentially causing unintended artifacts.
I included a separate change to the theming guide as well to ensure that the CSS custom property names are documented to help reduce confusion.
Fixes #123

fix(theme): use hex value without opacity for `border-color` theme style

---

src/lib/core/utils/event-utils.ts
src/lib/core/utils/index.ts
src/lib/drawer/base/base-drawer-adapter.ts
src/lib/drawer/base/base-drawer-foundation.ts

Fixes #130  
It was discovered that because the scroll container for this element is within the shadow dom of the drawer that the `scroll` event was not making it past the shadow root of the element. This is standard browser functionality.
The fix is to capture the scroll event from within the shadow dom and then manually dispatch a new `scroll` event from the drawer host element. This allows the capturing window scroll listener on the popup component to execute and fix the anchored positioning.

fix(drawer): fixed popup positioning within scrollable drawer content

---

src/lib/select/select/select-adapter.ts
src/lib/select/select/select-foundation.ts
src/lib/select/select/select.html
src/lib/select/select/select.scss
src/lib/select/select/select.ts
src/test/spec/select/select-component-delegate.spec.ts
src/test/spec/select/select.spec.ts

Fixes the accessibility of the component by ensuring that options and state are announced properly by screen readers. The focus has been moved from the internal selected text element to the host element to ensure that the options are announced properly.
Migrated these changes from TCW:
https://github.com/tyler-technologies/tyler-components-web/pull/768

fix(select): fix a11y when navigating options via keyboard and screen reader

---

src/stories/src/components/fab/fab.mdx

The FAB docs were not updated to reflect the latest CSS custom property changes between TCW 1.x and Forge 2.0. This change fixes one of CSS custom properties that is documented incorrectly.
We really need to automate the docs generation soon...

chore(docs): fix css custom prop docs for floating action button

---

src/stories/src/components/chip-field/chip-field.mdx

Fixes #132 
Adds the missing inherited "field" slot names to the chip-field docs. I did not update the constants file because this component inherits from the abstract field implementation (the shared slot names are located in the field constants file).

docs(chip-field): add missing slot docs

---

src/lib/button-toggle/button-toggle-group/button-toggle-group-foundation.ts
src/test/spec/button-toggle/button-toggle.spec.ts

The button-toggle-group change event was coercing falsy values (such as `0`) to `null` instead of explicitly checking for `null` or `undefined`. This change allows falsy values to flow through from the button-toggle component.

fix(button-toggle-group): allow falsy values in change event

---

src/demo/scripts/time-picker.js
src/lib/time-picker/time-picker-constants.ts
src/lib/time-picker/time-picker-foundation.ts
src/lib/time-picker/time-picker.ts
src/stories/src/components/time-picker/time-picker-args.ts
src/stories/src/components/time-picker/time-picker.mdx
src/stories/src/components/time-picker/time-picker.stories.tsx
src/test/spec/time-picker/time-picker.spec.ts

- Tests for the changes have been added: [Y]
- Docs have been added / updated: [Y]
Remove hours from the time picker dropdown, so "Now" is the only menu item. This will prevent the issue where a user types in a value with minute (e.g. 11:21) then opens the dropdown, the hour rounded down (11:00) gets selected, then tabbing off removes the minutes.
[NWARCH-1135](https://tylerjira.tylertech.com/browse/NWARCH-1135)

feat: showHourOptions for time-picker

---

src/lib/table/table.ts

The table will now automatically import and define the checkbox component as a dependency when it is used. This fixes an issue where if a developer was not using the checkbox previously that it would get defined and the select column would operate properly.
Fixes #147

fix(table): add checkbox to component dependencies

---

src/lib/file-picker/_mixins.scss

Move the helper text styles to the slotted element to ensure that the dimensions only apply if there are nodes assigned to the slot.
Fixes #140

fix(file-picker): fix helper text slotted styles and dimensions

---

src/lib/drawer/base/base-drawer-foundation.ts
src/lib/drawer/modal-drawer/modal-drawer-foundation.ts
src/test/spec/drawer/modal-drawer.spec.ts

- Does this PR introduce a breaking change? Y
The initialization logic has been updated to remove the ability for animations to execute. This ensures that the appropriate CSS classes are applied based on the default open state of the component when added to the DOM.
Fixes #148

fix(drawer): fixes drawer initialization state when defaulting to closed

---

src/lib/chip-field/chip-field-adapter.ts
src/lib/field/field-adapter.ts
src/lib/field/field-foundation.ts
src/lib/quantity-field/_mixins.scss
src/lib/quantity-field/quantity-field-adapter.ts
src/lib/quantity-field/quantity-field-foundation.ts
src/lib/text-field/text-field-adapter.ts

The original bug where `::before` and `::after` pseudo elements were not supported on `::slotted` selectors such as `::slotted(label)::before` in WebKit was fixed in 2021 (introduced in Safari 15). See ticket [here](https://bugs.webkit.org/show_bug.cgi?id=178237).
Our workaround was to use JavaScript in Safari to manually add the asterisk character to form field labels, but now that this has been fixed it was causing duplicate asterisks. We can safely remove this and tell consumers to use the latest Safari browser version. …

fix: fixed duplicate asterisk characters on required form field labels in Safari

---

src/demo/index.html
src/lib/app-bar/profile-button/app-bar-profile-button-adapter.ts
src/lib/app-bar/profile-button/app-bar-profile-button-constants.ts
src/lib/app-bar/profile-button/app-bar-profile-button-foundation.ts
src/lib/app-bar/profile-button/app-bar-profile-button.ts
src/lib/profile-card/profile-card-adapter.ts
src/lib/profile-card/profile-card-constants.ts
src/lib/profile-card/profile-card-foundation.ts
src/lib/profile-card/profile-card.html
src/lib/profile-card/profile-card.ts
src/stories/src/components/app-bar-profile/app-bar-profile.mdx
src/test/spec/app-bar/profile-button/app-bar-profile-button.spec.ts

Added new `signOutButtonText` and `profileButtonText` properties/attributes to the `<forge-app-bar-profile-button>` element and new `signOutText` and `profileText` properties/attributes to the `<forge-profile-card>` element. This enables developers to override the default text (unchanged) and implement i18n.
Closes #165

feat(app-bar-profile-button): allow for customizing the text on the sign out and profile buttons

---

src/lib/chip-field/_base.scss
src/lib/chip-field/_variables.scss
src/lib/chips/chip/_mixins.scss
src/lib/chips/chip/_variables.scss
src/stories/src/components/chips/chips.mdx

Chips will now expand in height to accommodate their content by using `height: auto` instead of static pixel values on a per-density basis. The pixel values are still applied, but these are now set as a `min-height` style for each density.
This shouldn't introduce a breaking change since anyone who was previously overriding `--forge-chip-height` can still do so and it will function as it did before. It's unlikely any applications were allowing for multi-line text to be clipped on purpose, in which case their layout may grow …

fix(chip): change default `height` style to use `auto` to accommodate content height

---

src/lib/table/table-utils.ts
src/stories/src/components/table/table.mdx

The table will now properly scope its queries for `<input type="checkbox">` elements to only the selection column cells. This will allow any checkboxes to be used in the filter row in non-select column cells.
Fixes #133 (this change removes the need for the `forge-ignore` attribute on checkbox filter elements)

fix(table): ignore filter row checkboxes when toggling select column state

---

.github/workflows/auto-pr-check.yml

Add `ci --ignore-scripts` to pr-check workflow installation to avoid installing unnecessary Storybook deps by default

chore: optimize pr-check workflow to limit dependency installation to

---

src/lib/table/_mixins.scss

The `<forge-select>` was using its default height when placed in a table column filter. This was inconsistent with the height adjustment that is applied to the `<forge-text-field>` by the `<forge-table>` component styles. This change adds a CSS custom property to override the `<forge-select>` height to match that of the `<forge-text-field>`.

fix(table): fixed default select height in column filter

---

src/lib/badge/_mixins.scss
src/lib/badge/badge.html
src/stories/src/components/badge/badge-arg-types.ts
src/stories/src/components/badge/badge.mdx
src/stories/src/components/badge/badge.stories.tsx

Closes #183 
Added leading and trailing slots to the root element of the badge. The root element has also been made into a flex container with `align-items` set to `center` and `--forge-icon-font-size` has been set to `14px` on the host element, allowing content including icons to lay out predictably by default.

feat(badge): added leading and trailing slots with support for icons

---

src/stories/src/components/button-toggle/button-toggle.mdx

Updates simple spelling error in the docs.

docs(button-toggle): corrects spelling error

---

src/lib/button-toggle/button-toggle-group/button-toggle-group-constants.ts
src/lib/button-toggle/button-toggle-group/button-toggle-group.ts

Added `forge-button-toggle-group-change` to the global `HTMLElementEventMap` type, and ensured that the default generic provides an `any` type.
This was found when attempting to implement within an Angular app and noticed the typings were missing.

fix(button-toggle-group): fixed `forge-button-toggle-group-change` typings

---

src/lib/autocomplete/autocomplete-adapter.ts
src/lib/autocomplete/autocomplete-foundation.ts
src/lib/select/core/base-select-adapter.ts
src/lib/select/core/base-select-foundation.ts

The select and autocomplete will now update the position of the dropdown after an option is selected. This accounts for scenarios where the field position could get updated between frames when selecting an option, which was causing the dropdown to appear visually disconnected from its corresponding field.
Fixes #196

update select and autocomplete dropdown position when options are selected

---

src/lib/menu/menu-foundation.ts
src/test/spec/menu/menu.spec.ts

This only occurs if the options were using the deprecated `icon` property to specify the leading icon. We map that `icon` property to the newer `leadingIcon` property for backwards compatibility in the options that are provided, but this was not happening if the options were set while the dropdown is open. This change ensures that this property is correctly mapped in this scenario.

[menu] fixed leading icon if options are reset while dropdown is open

---

src/lib/core/utils/utils.ts
src/lib/select/core/base-select-adapter.ts
src/test/spec/select/select.spec.ts

Added a new utility function to copy properties from one object to another only where the properties exist in both objects. This is much like `Object.assign()` but ensures we only copy properties that we care about.
The select will now properly apply properties from configuration-based options to the underlying `<forge-option>` and `<forge-option-group>` elements.
Fixes #177

fix(select): copy all configuration-based option properties to underlying option elements

---

src/lib/expansion-panel/expansion-panel-foundation.ts
src/test/spec/expansion-panel/expansion-panel.spec.ts

All keydown events will now propagate except for the `Space` and `Enter` keys which we use for toggling the open state. We need these events to stop propagation for cases where there are nested expansion panels. All other key events should be able to propagate fine now.
This bug was discovered in an app where trapping focus was necessary, but the `Tab` keydown event was not propagating to their document-level listener. A workaround was provided to use a capturing listener.

fix(expansion-panel): allow keydown events to propagate except for toggle keys

---

src/lib/split-view/split-view-panel/split-view-panel.ts
src/lib/split-view/split-view/split-view.ts

- Tests for the changes have been added: n/a
- Docs have been added / updated: n/a
Adding JSDoc comments so the custom elements manifest is sufficient for proxy component generation in `forge-angular` repo.
Would be nice to have some linting to enforce this, which might be possible using [eslint-plugin-jsdoc](https://www.npmjs.com/package/eslint-plugin-jsdoc).  I can open up an issue to track that.

docs(split-view): add JSDoc for manifest

---

src/lib/split-view/split-view-panel/split-view-panel-foundation.ts
src/lib/split-view/split-view/split-view-adapter.ts
src/lib/split-view/split-view/split-view-foundation.ts
src/test/spec/split-view/split-view/split-view.spec.ts

Closes #201 
When a split view resizes closed panels will no longer have their size set to zero when reopening. To cover edge cases panels are refit and their sizing recalculated after every open and close event.

fix(split-view): avoid updating size and accessibility of closed panels

---

src/lib/select/core/base-select-adapter.ts
src/lib/select/core/base-select-foundation.ts
src/lib/select/option/option-constants.ts
src/lib/select/option/option-foundation.ts
src/test/spec/select/select.spec.ts

The select component was not updating its selection state if child `<forge-option>` elements change their `value` property. This was causing issues where a value being set on the `<forge-select>` would not reflect in the UI if the `<forge-option>` values are set **after** the `<forge-select>` value...
The new behavior is that the `<forge-option>` elements will now dispatch a `forge-option-value-change` event when the `value` setter is executed. This is intended to be an internal use only event that will not be documented. This …

fix(select): fixed a bug where the UI was not reflecting the selected value if the option values are changed after the component value is set

---

src/lib/switch/switch.ts
src/test/spec/switch/switch.spec.ts

- Tests for the changes have been added: [Y]
- Docs have been added / updated: [N]
The switch component will now always force its UI updates after the `forge-switch-select` event if the event is not cancelled to the same value provided in the event `detail`. This will ensure that the state cannot get out of sync with the UI, and ensures that if developers attempt to incorrectly toggle the state value from within the event listener that it won't get out of sync with the internal component state.
If developers need to update the state of the components `selected` property manually, they should always …

fix(switch): fixed a bug where the UI could incorrectly reflect the component state

---

src/lib/split-view/split-view-panel/split-view-panel-adapter.ts
src/lib/split-view/split-view-panel/split-view-panel-constants.ts
src/lib/split-view/split-view-panel/split-view-panel-foundation.ts
src/lib/split-view/split-view-panel/split-view-panel-utils.ts
src/lib/split-view/split-view/split-view-constants.ts
src/test/spec/split-view/split-view-panel/split-view-panel.spec.ts

Added a transparent viewport-sized div above other body content while dragging a split view panel's handle to prevent other contexts like iframes from interfering with listeners added to the document body while the pointer is over them. After dragging has stopped the div is removed. This also has the benefit of more easily maintaining a cursor style while dragging and preventing potentially destructive style mutations to the body by setting cursor styles to the div instead.
Fixes #221

fix(split-view): add overlay to body while dragging to prevent context loss

---

src/lib/field/_base.scss
src/lib/field/_variables.scss

Removed the ::before pseudo element which will simplify the structure to allow for multi-line text. Removed text-baseline and margin-top items from the $helper-text map as they are no longer needed.
Fixes #219

fix(field): fixed a bug where height of helper-text element was incorrect

---

src/lib/date-range-picker/date-range-picker-foundation.ts

The updated changes now correctly populate the end date when pressing 't' while the calendar is open.
Date range validation (_isDateRangeAcceptable) was also implemented to prevent invalid or negative date ranges.
Fixes #139

fix(date-range-picker): fixed a bug that allowed invalid date ranges

---

src/lib/list/list-item/list-item-adapter.ts
src/lib/list/list-item/list-item-foundation.ts
src/lib/list/list-item/list-item.ts
src/test/spec/list/list-item/list-item.spec.ts

- Tests for the changes have been added: [Y]
- Docs have been added / updated: [N]
The `forge-list-item` component will now properly toggle it's child checkbox component on initialization if the parent `forge-list` has an initial `selectedValue` provided. It does this by attempting to call the tryToggleCheckboxRadio when trySelect is called.
The `forge-list-item` component was not updating it's child checkbox state when Angular application was databinding the `selectedValue` and a `forge-list` component and it's `forge-list-item` components were dynamically rendered in a ngFor.

fix(list-item): fixed a bug where the UI could incorrectly reflect the component state

---

src/lib/list/list-item/list-item-adapter.ts
src/lib/list/list-item/list-item-foundation.ts
src/test/spec/list/list-item/list-item.spec.ts

Fixes #230 
- Docs have been added / updated: n/a
A clear and concise description of the changes, including an breaking changes (if applicable)
Required a slight modification to the pattern used in #115 for icon-button because list-item has a `ripple` property that allows the ripple to be turned on and off.  I suspect it's an extreme edge case for this property to be set after initialization, but I think the logic should ensure a consistent state regardless.

perf(list-item): delay ripple creation

---

.github/workflows/build-pr.yml
.github/workflows/build-release.yml
.github/workflows/deploy-pr.yml

The PR build workflows have been altered to separate the temporary Storybook deployment from the `build-pr.yml` workflow. This is to allow us to opt-in to deploying a Storybook build for a PR via a label instead of having it happen automatically for every PR.
The reason for this is to allow for us to choose when we want to deploy Storybook for PRs in case it isn't necessary, or if we choose to use Codeflow or pull to local instead for testing.
The Storybook deployment will only be triggered when adding the `storybook-preview` …

chore: separate temp storybook deployment from build-pr workflow

---

src/dev/pages/autocomplete/autocomplete.ts
src/lib/autocomplete/autocomplete.ts

The autocomplete component will now auto-define the `arrow_drop_down` icon that is commonly used with this component for convenience.
Fixes #217

fix(autocomplete): always define the `arrow_drop_down` icon

---

src/lib/date-picker/base/base-date-picker.ts
src/lib/date-range-picker/date-range-picker-foundation.ts
src/stories/src/components/date-range-picker/date-range-picker.mdx
src/test/spec/date-range-picker/date-range-picker.spec.ts

The date-range-picker will now accept `null`, `undefined`, or any other falsy value to "clear" the current value in the component.
Also, removed an internally used TypeScript interface from the public component API docs in Storybook.
Fixes #258

fix(date-range-picker): allow for setting `value` to `null` to clear the component value

---

src/lib/app-bar/notification-button/app-bar-notification-button-adapter.ts
src/lib/app-bar/notification-button/app-bar-notification-button-constants.ts
src/lib/app-bar/notification-button/app-bar-notification-button-foundation.ts
src/lib/app-bar/notification-button/app-bar-notification-button.html
src/lib/app-bar/notification-button/app-bar-notification-button.ts
src/stories/src/components/app-bar-notifications/app-bar-notifications-args.ts
src/stories/src/components/app-bar-notifications/app-bar-notifications.mdx
src/stories/src/components/app-bar-notifications/app-bar-notifications.stories.tsx
src/test/spec/app-bar/notification-button/app-bar-notification-button.spec.ts

- Tests for the changes have been added: [Y]
- Docs have been added / updated: [Y]
- I have linked any related GitHub issues to be closed when this PR is merged? [Y]
Changes the app-bar-notification-button to allow a consuming developer to specify an alternative icon to the default.
Add any other context about the change here.

feat(app-bar-notification-button): allow icon to be set to a user specificied icon

---

src/lib/autocomplete/autocomplete-adapter.ts
src/lib/autocomplete/autocomplete-constants.ts
src/lib/autocomplete/autocomplete-foundation.ts
src/lib/autocomplete/autocomplete-utils.ts
src/lib/autocomplete/autocomplete.ts
src/lib/list-dropdown/list-dropdown-constants.ts
src/lib/list-dropdown/list-dropdown-utils.ts
src/stories/src/components/autocomplete/autocomplete.mdx

The autocomplete will no longer reference the `IOption` interface from the select component. It introduces a new `IAutocompleteOption` interface (which inherits the same properties as `IOption` to avoid breaking changes). This allows access to list-dropdown properties such as `leadingIcon` that were previously not available in the typings, even though they could technically be provided.
A small fix for the render order of the leading icon/builder content when in multiple mode was included as well.
Fixes #271
Fixes #272

fix(autocomplete): fixed typings and leading icon render order

---

src/dev/pages/list/list.ejs
src/lib/list-dropdown/list-dropdown-aware-foundation.ts
src/lib/list-dropdown/list-dropdown-aware.ts
src/lib/list-dropdown/list-dropdown-constants.ts
src/lib/list-dropdown/list-dropdown-utils.ts
src/lib/list/list-item/_mixins.scss
src/lib/list/list-item/_variables.scss
src/lib/popup/popup-constants.ts
src/lib/popup/popup.scss
src/lib/select/core/base-select-constants.ts
src/lib/select/core/base-select-foundation.ts
src/lib/select/select/select.ts
src/stories/src/components/popup/popup.mdx
src/stories/src/components/select/select-args.ts
src/stories/src/components/select/select.mdx
src/stories/src/components/select/select.stories.tsx

- [list-item] fixed the list-item component to ensure that setting the `wrap` property/attribute will allow text to wrap on slotted elements.
- [select] added new properties/attributes to the select component to allow for controlling whether the popup will allow for options to wrap or not. We may want to make this the default, but in an effort to avoid breaking changes we have made this opt-in.
- [popup] added the ability to specify if the popup should constrain itself to the width of the viewport as a `max-width`.
- [select] …

[list-item][select] allow list-item/option text to wrap

---

src/lib/button/button.ts
src/lib/checkbox/checkbox-adapter.ts
src/lib/checkbox/checkbox-foundation.ts
src/lib/dialog/dialog-adapter.ts
src/lib/dialog/dialog-foundation.ts
src/lib/icon-button/icon-button.ts
src/lib/list/list-item/list-item-foundation.ts
src/lib/radio/radio-adapter.ts
src/lib/radio/radio-foundation.ts
src/lib/ripple/forge-ripple.ts
src/lib/switch/switch.ts

Several related changes were made regarding performance concerns with how/when the MDC ripple is instantiated. Overall the goal is to delay ripple instantiation until first user interaction to avoid the overhead the ripple causes.
Changes made:
- Delay ripple instantiation until first user interaction on checkbox, radio, and switch
- Remove unnecessary `layout()` method calls in the checkbox when toggling checked state
- Tested with 1000 checkboxes on a page and noticed very little lag after this change.
- Remove legacy code …

perf: checkbox, radio, and switch will now instantiate ripple upon first user interaction

---

src/dev/pages/linear-progress/linear-progress.ts
src/lib/linear-progress/linear-progress.ts
src/stories/src/components/linear-progress/code/linear-progress-determinate.ts
src/stories/src/components/linear-progress/linear-progress.mdx
src/test/spec/linear-progress/linear-progress.spec.ts

The default `buffer` value was set to `0` previously which meant that every time the `determinate` mode was was used that developers have to set the `buffer` property to `1`. This is inconvenient and we should cater to the more common use case.
This component will now default the `buffer` state to `1` which means that you won't see the buffering dots animation when just using the default determinate mode now. A developer will no longer need to set the `buffer` state to `1` manually every time they want to use a determinate …

fix(linear-progress): updated the default `buffer` state to be `1` instead of `0`

---

src/dev/pages/button/button.ejs
src/dev/pages/button/button.scss
src/dev/pages/button/button.ts
src/dev/pages/fab/fab.ejs
src/dev/pages/fab/fab.ts
src/dev/pages/icon-button/icon-button.ejs
src/dev/pages/icon-button/icon-button.ts
src/lib/button/button-constants.ts
src/lib/button/button.ts
src/lib/floating-action-button/floating-action-button-constants.ts
src/lib/icon-button/icon-button-constants.ts
src/stories/src/components/button/button.mdx
src/stories/src/components/fab/fab.mdx
src/stories/src/components/icon-button/icon-button.mdx

The `<forge-button>`, `<forge-icon-button>` and `<forge-fab>` components now all supports providing an `<a>` tag as a child in place of the standard `<button>` element.
Closes #275

feat: allow for using `<a>` element in place of `<button>` in `<forge-button>`, `<forge-icon-button>` and `<forge-fab>` components

---

src/lib/table/table-utils.ts
src/test/spec/table/table.spec.ts

The `cursor: pointer` style will now properly stay applied on all `<tr>` elements within `<tbody>` when re-rendering the data.
Fixes #287

fix(table): fixed a bug where the `pointer` cursor could be lost when `allowRowClick` is enabled

---

src/lib/autocomplete/autocomplete-foundation.ts
src/test/spec/autocomplete/autocomplete.spec.ts

The dropdown will now stay open when selecting items when `mode` equals `'stateless'` and `multiple` is enabled. This allows for more easily selecting multiple items without the dropdown closing after each selection to be consistent with the default stateful mode of this component.
Fixes #268

fix(autocomplete): keep dropdown open when selecting items in stateless + multiple mode

---

src/dev/index.ejs
src/dev/src/index.ts
src/lib/core/utils/utils.ts
src/lib/select/core/base-select-adapter.ts
src/lib/select/core/select-utils.ts
src/lib/select/option-group/option-group.ts
src/test/spec/select/select.spec.ts
src/tsconfig-test.json

The `builder` property on `<forge-option-group>` elements (among other properties) will now correctly propagate to the list-dropdown.
Fixes #260

fix(select): fixed a bug where the option group `builder` property was not being called

---

src/dev/pages/table/table.ts
src/lib/table/table-utils.ts
src/lib/table/types.ts
src/stories/src/components/table/table.mdx

The `TableTemplateBuilder` callback (the `template` property on a column configuration) will now provide the column index to the callback for convenience to avoid the need for developers to perform a lookup on the index.
Along with this change, there is a new separate `type` created for the expandable row functionality since they shared the same `TableTemplateBuilder` type but in the context of a row expanding there is no specific column associated. This callback will use the same type just named different but without the …

feat(table): provided the column index to the `TableTemplateBuilder`

---

src/lib/file-picker/file-picker-adapter.ts
src/lib/file-picker/file-picker-foundation.ts
src/lib/file-picker/file-picker.ts

The file-picker component will now gracefully handle a child `<button>` element not being in the DOM during instead of throwing an exception assuming it is there when setting the `disabled` property.
Fixes #188

fix(file-picker): allow for setting disabled state before child `<button>` is in DOM

---

src/dev/pages/toolbar/toolbar.html
src/dev/pages/toolbar/toolbar.scss
src/dev/pages/toolbar/toolbar.ts
src/lib/toolbar/_mixins.scss
src/lib/toolbar/toolbar.html
src/lib/toolbar/toolbar.scss
src/stories/src/components/toolbar/toolbar.mdx

- Added new `no-padding` attribute (no JavaScript property) to set internal `padding-inline` to `0`
- Added new `auto-height` attribute (no JavaScript property) to set internal `height` to `auto` for dynamically sized toolbars
- Switched from using both `padding-left` and `padding-right` to only `padding-inline`. This allows for setting the inline padding with a single property and to enable developers to customize the start (previously left) and end (previously right) padding separately.
- Added a default (unnamed) slot. This …

feat(toolbar): various toolbar improvements

---

src/lib/list/list-item/_mixins.scss

Nothing has been changed functionally or visually. We were previously applying the `baseline-top` mixin from MDC to slotted elements, but since we weren't providing the value with a `px` suffix it was actually not applying the `height` properly and leaving the unused `::before` pseudo element in the DOM for no reason.
We can safely remove this mixin because our design does not require it.
Fixes #254

fix(list-item): remove unused `::before` pseudo element from slotted elements

---

src/lib/field/_base.scss
src/lib/field/_selector.scss
src/stories/src/components/chip-field/chip-field.mdx
src/stories/src/components/select/select.mdx
src/stories/src/components/text-field/text-field.mdx

The following CSS custom properties have been added:
- select: `--forge-select-border-style`
- text-field: `--forge-text-field-border-display`
- chip-field: `--forge-chip-field-border-display`
The docs have been updated to reflect this in Storybook.
Fixes #175 
The old name referenced in the issue (`--forge-select-border-display`) was renamed to more obvious to what it now controls and that note has been removed from the docs as it was an artifact from the legacy library.

feat: added CSS custom property for controlling the internal `border-style` on select, text-field, and chip-field

---

src/lib/menu/menu-constants.ts
src/lib/menu/menu-foundation.ts
src/lib/menu/menu.ts
src/test/spec/menu/menu.spec.ts

- Updated selector list for detecting toggle elements
- Updated the `connectedCallback()` to wait for a specific toggle element from the selector list before initializing
- Use the `focusout` event instead of `blur` to allow for detecting focus being lost from any child element (nested or not)
Fixes #249

fix(menu): fixed toggle element initialization

---

src/dev/pages/chip-field/chip-field.ejs
src/lib/chip-field/_selector.scss
src/lib/chip-field/chip-field.scss

The `addon-end` container will now properly grow with the field height.
Some other internal styles were not being applied properly due to incorrect selector nesting, such as height CSS custom properties, and those will now work properly as well as a side effect of this.
Fixes #216

fix(chip-field): fixed a bug where addon-end slot was not expanding full height as the field grew

---

src/dev/pages/quantity-field/quantity-field.ejs
src/dev/pages/quantity-field/quantity-field.html
src/dev/pages/quantity-field/quantity-field.ts
src/dev/src/components.json
src/lib/quantity-field/quantity-field-adapter.ts
src/lib/quantity-field/quantity-field-foundation.ts
src/lib/quantity-field/quantity-field.ts
src/stories/src/components/quantity-field/quantity-field.mdx

The `<forge-quantity-field>` will now attempt to set `tabindex="-1"` on the increment and decrement `<button>` elements during initialization (if a `tabindex` attribute does not already exist). This allows for developers to opt-in to including them in the tab order if they choose, otherwise for keyboard users the up & down arrow keys control the increment and decrement actions respectively.
Fixes #253

fix(quantity-field): remove increment and decrement buttons from the tab order by default

---

src/lib/autocomplete/autocomplete-foundation.ts
src/lib/calendar/calendar-foundation.ts
src/lib/date-picker/base/base-date-picker-foundation.ts
src/lib/menu/menu-foundation.ts
src/lib/select/core/base-select-foundation.ts
src/lib/time-picker/time-picker-foundation.ts

All components that currently handle the `Escape` key will now call `stopPropagation()` on the `keydown` event (if they are handling it themselves) so that it doesn't bubble to other elements, such as the `<forge-dialog>` causing it to inadvertently close as well.
Fixes #300

fix: stop propagation on `Escape` key events

---

src/lib/dialog/dialog-foundation.ts
src/test/spec/dialog/dialog.spec.ts

The dialog was incorrectly using `clientX` and `clientY` coordinates from the `mousedown` which has side effects if the page can scroll causing the element to be incorrectly positioned. The component will now properly utilize the `pageX` and `pageY` coordinates to account for this.

fix(dialog): fixed a bug where moving the dialog within a scroll container would calculate an incorrect position

---

src/lib/busy-indicator/_mixins.scss
src/lib/busy-indicator/busy-indicator.html

- Use `<div>` instead of `<aside>` since we set `role` anyway
- Replace `<h3>` with `<h1>`
- Hide `<forge-circular-progress>` and `<forge-linear-progress>` from the AOM using `aria-hidden="true"` because these elements are intended to decorative.
- Use an ARIA live region on the message text and convert to a `<p>` tag.
Fixes #255

fix(busy-indicator): fixed various accessibility issues

---

src/dev/pages/time-picker/time-picker.html
src/lib/core/mask/intermediate-time-parser.ts
src/lib/core/mask/time-input-mask.ts
src/lib/core/mask/time-segment-parser.ts
src/lib/core/utils/time-utils.ts
src/lib/list-dropdown/list-dropdown-adapter.ts
src/lib/list-dropdown/list-dropdown-constants.ts
src/lib/list-dropdown/list-dropdown-foundation.ts
src/lib/list-dropdown/list-dropdown-utils.ts
src/lib/time-picker/time-picker-adapter.ts
src/lib/time-picker/time-picker-component-delegate.ts
src/lib/time-picker/time-picker-foundation.ts
src/lib/tooltip/tooltip-foundation.ts
src/lib/tooltip/tooltip.ts
src/test/spec/menu/menu.spec.ts
src/test/spec/time-picker/time-picker.spec.ts
src/test/spec/tooltip/tooltip.spec.ts

Refactored the input masking logic with custom rules to improve usability and ease of entry.
In general the entry will follow that native `<input type="time">` more closely, along with some minor improvements for convenience. Each segment will automatically pad a leading zero upon first entry, and attempt to shift values over within a segment if possible.
Fixes #228

fix(time-picker): improve input mask usability

---

src/lib/app-bar/profile-button/app-bar-profile-button-adapter.ts
src/lib/app-bar/profile-button/app-bar-profile-button-constants.ts
src/lib/app-bar/profile-button/app-bar-profile-button-foundation.ts
src/lib/app-bar/profile-button/app-bar-profile-button.ts
src/lib/profile-card/profile-card-adapter.ts
src/lib/profile-card/profile-card-constants.ts
src/lib/profile-card/profile-card-foundation.ts
src/lib/profile-card/profile-card.ts
src/stories/src/components/app-bar-profile/app-bar-profile-args.ts
src/stories/src/components/app-bar-profile/app-bar-profile.mdx
src/stories/src/components/app-bar-profile/app-bar-profile.stories.tsx
src/test/spec/app-bar/profile-button/app-bar-profile-button.spec.ts

Added the ability to provide an icon name to be rendered within the `<forge-avatar>` element. This requires that the icon be registered with the `IconRegistry`, and it will take precedence over the `avatarText` and `avatarImageUrl` values.
The reason for this change is to support applications that don't have user first/last name information to instead render a generic icon.

feat(app-bar-profile-button): added new `avatarIcon` property to allow for rendering an icon from the `IconRegistry` instead of text

---

src/lib/stack/_mixins.scss
src/lib/stack/stack.scss
src/stories/src/components/stack/stack.mdx

- Does this PR introduce a breaking change? 
- Remove the default `height: 100%` style that is applied to the host element by default since this could lead to confusion, and can easily be set by consumers already. This style will now only be applied when `stretch` is used while **not** `inline`.
- Swapped the `flex-grow` style property to reference the shorthand `flex` style for more flexibility, as well as a better default for stretched stack items.

fix(stack): fix stretch styles

---

src/lib/select/core/base-select-foundation.ts
src/test/spec/select/select.spec.ts

Filtering options while using caps lock or the shift key will now properly use a case-insensitive "starts with" strategy.
Fixes #316

fix(select): fixed a bug where filtering options with uppercase letters was not working

---

src/lib/autocomplete/autocomplete-foundation.ts
src/lib/select/core/base-select-foundation.ts
src/test/spec/autocomplete/autocomplete.spec.ts
src/test/spec/select/select.spec.ts

When selecting a single option in multiple mode in both the select and autocomplete, the "selected text" will now default to showing the option label instead of "1 option selected". If more than one option is selected, it will still display the text "x options selected" as it previously did.
Fixes #310

fix(select, autocomplete): show option label when one option is selected in multiple mode

---

src/dev/pages/autocomplete/autocomplete.html
src/dev/pages/autocomplete/autocomplete.ts
src/lib/autocomplete/autocomplete-constants.ts
src/lib/autocomplete/autocomplete-foundation.ts
src/lib/autocomplete/autocomplete.ts
src/stories/src/components/autocomplete/autocomplete-args.ts
src/stories/src/components/autocomplete/autocomplete.mdx
src/stories/src/components/autocomplete/autocomplete.stories.tsx
src/test/spec/autocomplete/autocomplete.spec.ts

When filtering options by typing, the dropdown will focus the first option automatically. This change adds a new `filterFocusFirst` configuration property that defaults to `true` to retain the existing functionality, but allows for a developer to set it to `false` to stop the first option from being automatically focused if desired.
This came up due to an application needing to allow for submitting a form via the enter key (specifically when using `allowUnmatched` and composed with a chip-field), and it was confusing for …

feat(autocomplete): add `filterFocusFirst` property

---

src/lib/date-picker/base/base-date-picker-foundation.ts
src/test/spec/date-picker/date-picker.spec.ts

Updated the logic that determines if the provided date value is "acceptable" (passes min, max, disabled day checks) to ignore those checks if the component is configured to allow invalid (unacceptable) dates.
This allows for the change event to be dispatched properly when the developer wants to provide these guard rails while still providing separate error messages to the user.
Fixes #324

fix(date-picker): always dispatch the change event when a valid date is entered if `allowInvalidDate` is `true`

---

src/lib/split-view/split-view/split-view-adapter.ts
src/test/spec/split-view/split-view/split-view.spec.ts

Fixes #327 
This changes the `getSlottedPanels()` method of the split view adapter to match the parent element of queried panels against the component instance. Before, the method would return all panels nested within the split view instead of just those that should be directly managed by it.

fix(split-view): query only immediate child panels

---

src/lib/autocomplete/autocomplete-adapter.ts
src/lib/autocomplete/autocomplete-foundation.ts
src/lib/list-dropdown/list-dropdown-adapter.ts
src/lib/list-dropdown/list-dropdown-utils.ts
src/test/spec/list-dropdown/list-dropdown.spec.ts
src/test/spec/select/select-dropdown.spec.ts

The autocomplete will now only toggle the specific option that was clicked when selecting a dynamically added option in an infinite scroll scenario.
This change relies on the standard selection functionality of the underlying list item instead of manually calculating the option index and toggling the selected state.
Along with this change, the underlying option `id` of each dynamically appended option will now be unique.
Previously the component was manually toggling the selected list items when they were clicked, which …

fix(autocomplete): fixed a bug where selecting appended options in multiple mode would incorrectly select the wrong options in the UI dropdown

---

src/lib/paginator/paginator-foundation.ts
src/test/spec/paginator/paginator.spec.ts

The page size select will now properly reflect the current page size selection value when changed by the user.
Fixes #332 
This was a regression caused by a [recent change](https://github.com/tyler-technologies-oss/forge/pull/212) in the select component where some state synchronization was fixed, but this component was not updated. Unit tests have been added to detect this situation in the future.

fix(paginator): fixed a bug where the paginator was not reflecting the current page size after selection in the page size select

---

src/dev/pages/focus-indicator/focus-indicator.ejs
src/dev/pages/focus-indicator/focus-indicator.html
src/dev/pages/focus-indicator/focus-indicator.scss
src/dev/pages/focus-indicator/focus-indicator.ts
src/dev/src/components.json
src/lib/focus-indicator/_mixins.scss
src/lib/focus-indicator/_variables.scss
src/lib/focus-indicator/build.json
src/lib/focus-indicator/focus-indicator-adapter.ts
src/lib/focus-indicator/focus-indicator-constants.ts
src/lib/focus-indicator/focus-indicator-foundation.ts
src/lib/focus-indicator/focus-indicator.html
src/lib/focus-indicator/focus-indicator.scss
src/lib/focus-indicator/focus-indicator.test.ts
src/lib/focus-indicator/focus-indicator.ts
src/lib/focus-indicator/index.ts
src/lib/index.ts
src/lib/slider/_mixins.scss
src/lib/slider/slider-utils.ts
src/lib/slider/slider.html
src/lib/slider/slider.ts
src/lib/tabs/tab/_mixins.scss
src/lib/tabs/tab/tab-adapter.ts
src/lib/tabs/tab/tab-constants.ts
src/lib/tabs/tab/tab.html
src/lib/tabs/tab/tab.ts
web-test-runner.config.mjs

With `:focus-visible` being well-supported in browsers now, we needed to provide a way to show keyboard focus only, instead of relying on the states styles from the ripple implementation.
Going forward the ripple will no longer be used on any components to convey focus. Elements will either provide their own focus states, or utilize the `<forge-focus-indicator>` to provide a "focus ring" to elements via `:focus-visible`. The ripple will be refactored in the near future to no longer provide a resting focused state, and …

feat: created a new `<forge-focus-indicator>` component (for `:focus-visible` support)

---

src/lib/chips/chip/_mixins.scss

The `<forge-chip>` now sets `text-align: center` on the internal text content container element. This ensures that the text is always centered horizontally regardless of the width of the content in relation to the chip width.
Fixes #336

fix(chips): fixed a bug where the text was not centered if the width was less than than the min-width of the chip

---

src/lib/stepper/core/stepper-utils.ts
src/lib/stepper/stepper/stepper-foundation.ts
src/test/spec/stepper/stepper.spec.ts

- Does this PR introduce a breaking change? Y
Settings the `steps` property will now properly inherit the `vertical` state from the `<forge-stepper>` when creating the `<forge-step>` elements.
Fixes #339

fix(stepper): fixed a bug where the `vertical` state was not being applied if the `steps` property was changed dynamically

---

src/lib/color-picker/color-picker-foundation.ts

The `<forge-color-picker>` will now accept manually entering a hex color value that is invalid. This means an invalid hex color value can technically be entered now, but the underlying color will not change until a valid hex value is received.
This change allows for incrementally entering a hex color value that will _eventually_ create a valid hex code.
Fixes #338

fix(color-picker): fixed a bug where manually entering a hex value would not accept characters until a valid hex string value and length was reached

---

src/dev/pages/date-picker/date-picker.html
src/dev/pages/date-picker/date-picker.ts
src/lib/calendar/calendar-dropdown/calendar-dropdown.ts
src/lib/date-picker/base/base-date-picker-adapter.ts
src/lib/date-picker/base/base-date-picker-constants.ts
src/lib/date-picker/base/base-date-picker-foundation.ts
src/lib/date-picker/base/base-date-picker.ts
src/stories/src/components/calendar/calendar.mdx
src/stories/src/components/date-picker/date-picker-args.ts
src/stories/src/components/date-picker/date-picker.mdx
src/stories/src/components/date-picker/date-picker.stories.tsx
src/stories/src/components/date-range-picker/date-range-picker-args.ts
src/stories/src/components/date-range-picker/date-range-picker.mdx
src/stories/src/components/date-range-picker/date-range-picker.stories.tsx

Added a new `locale` property/attribute to the `<forge-date-picker>` and `<forge-date-range-picker>` elements that will propagate to the underlying `<forge-calendar>` that is presented in the dropdown. This allows for setting the locale of the calendar through the date picker elements.
Fixes #343

fix(date-picker): fixed a bug where the `locale` of the calendar could not be set through the date picker element

---

src/lib/field/field-foundation.ts
src/test/spec/chip-field/chip-field.spec.ts

The `<forge-chip-field>` will now properly float its label when re-rendered while the label was previously already floating.
The underlying field logic that manages the floating label state was not properly destroying its floating label state when the element was removed from the DOM. This meant that when the component was re-added to the DOM, the field logic assumed the label was already floating and didn't need to float it.
Ensuring the DOM state was updated when the element was disconnected is all that needed to occur …

fix(chip-field): fix floating label state

---

package-lock.json
package.json
src/lib/app-bar/profile-button/app-bar-profile-button-adapter.ts
src/lib/autocomplete/autocomplete-adapter.ts
src/lib/busy-indicator/busy-indicator-adapter.ts
src/lib/chip-field/chip-field-foundation.ts
src/lib/chips/chip/chip-adapter.ts
src/lib/date-picker/date-picker-adapter.ts
src/lib/date-range-picker/date-range-picker-adapter.ts
src/lib/dialog/dialog-adapter.ts
src/lib/field/field-adapter.ts
src/lib/list/list/list-adapter.ts
src/lib/popup/popup-adapter.ts
src/lib/radio/radio-adapter.ts
src/lib/stepper/stepper/stepper-adapter.ts
src/lib/tabs/tab-bar/tab-bar-adapter.ts
src/lib/text-field/text-field-adapter.ts
src/lib/time-picker/time-picker-adapter.ts

An issue was presented where an element was adopted from its origin document into a new document (via a new window). The issue stemmed from the fact that there were checks in various components (specifically the autocomplete) where `document.activeElement` (from within the `getActiveElement()` utility function) was evaluating incorrectly in these scenarios due to the wrong `document` being used.
This change updates the calls to `getActiveElement()` to always use the `ownerDocument` of the component. This ensures that it …

fix: fixed a bug where detecting the active element after being adopted into a new document could incorrectly reflect the wrong element

---

src/lib/list/list-item/_mixins.scss
src/lib/list/list-item/_variables.scss

The list item component will now properly apply the dense height styles.
Fixes #357

fix(list-item): fixed a bug where setting `dense` wasn't applying the correct height

---

src/lib/popup/popup-adapter.ts
src/lib/popup/popup-foundation.ts
src/lib/popup/popup.ts
src/stories/src/components/popup/popup.mdx
src/test/spec/popup/popup.spec.ts

The `forge-popup-close` event now contains a reference to the `forge-popup` element in the event `detail`, so that it's possible to distinguish which popup is responsible for the event in the case where there are multiple (e.g. when clicking a menu item shows a popup).  Also emitting the close event from the host element, in addition to the target element, which also ensures a one-to-one relationship between the event and popup given you have a reference to it.  The latter might be more useful in JavaScript, while the …

feat(popup): add popup ref to close event, emit from host

---

src/lib/keyboard-shortcut/keyboard-shortcut-constants.ts
src/lib/keyboard-shortcut/keyboard-shortcut-foundation.ts
src/lib/keyboard-shortcut/keyboard-shortcut.ts
src/stories/src/components/keyboard-shortcut/keyboard-shortcut.mdx
src/test/spec/keyboard-shortcut/keyboard-shortcut.spec.ts

This adds a new `activateCallback` property as an alternative to requiring binding to the `keyboard-shortcut-activate` event to use the component. There are some situations where this method could be more concise than adding an event listener.

feat(keyboard-shortcut): add activate callback

---

src/lib/chip-field/chip-field-adapter.ts
src/test/spec/chip-field/chip-field.spec.ts

Fixes #380 
Don't propagate click events on the input container from the input if the input is disabled.
May want to reverify #289
Also going to look into fixing a two other issues, potentially could skip-release here to batch them in a single patch.

fix(chip-field): don't propagate click if disabled

---

src/lib/date-picker/base/base-date-picker-foundation.ts
src/lib/date-range-picker/date-range-picker-foundation.ts
src/lib/time-picker/time-picker-foundation.ts
src/test/spec/date-picker/date-picker.spec.ts
src/test/spec/date-range-picker/date-range-picker.spec.ts
src/test/spec/time-picker/time-picker.spec.ts

Fixes #375 
Mask was being conditionally applied after text selection was performed.  Swapping the order restores the desired behavior of being able to tab into the field and start typing without adjusting the cursor position.
May want to also reverify #318 
Can potentially apply skip-release label, still planning on investigating one more issue and we could batch the three together into a single patch release.

fix(date-picker, time-picker, date-range-picker): select mask on focus if shown

---

src/lib/chip-field/_base.scss
src/lib/chip-field/_selector.scss
src/lib/chip-field/chip-field.html
src/stories/src/components/chip-field/chip-field.mdx

Fixes #378
- Tests for the changes have been added/updated: n/a (layout)
Because the CSS grid formatting creates new rows if multiple elements target the same named grid lines, creating a single container to handle multiple leading/trailing icons, and exposing as CSS parts.  An example use case for needing two trailing icons is a Chips Autocomplete, with a dropdown arrow and a button to clear all selected chips.
The `grid-template-columns` existed longer than it was being used, but took effect with #290 fixing the reference to it, which is why this wasn't an issue until …

fix(chip-field): don't wrap leading/trailing icons

---

src/dev/pages/autocomplete/autocomplete.ejs
src/lib/autocomplete/autocomplete-foundation.ts

The filter text will now be cleared when using the built-in clear functionality, and this will be properly reflected in the highlighted text of the dropdown.
Fixes #389

fix(autocomplete): fixed a bug where the filter text was not getting removed when the clear button is clicked

---

src/lib/autocomplete/autocomplete-constants.ts
src/lib/autocomplete/autocomplete-foundation.ts
src/lib/autocomplete/autocomplete.ts
src/stories/src/components/autocomplete/autocomplete.mdx
src/test/spec/autocomplete/autocomplete.spec.ts

Added a new `forceFilter()` method to the element that will allow for a consumer to call it when their underlying options have changed. This will usually coincide with a `value` update as well, so calling `forceUpdate()` will force the component to throw any old options it has cached and synchronize its selected value with the new options (as long as the consumer has also provided the new options to their filter callback of course).
There is an edge case here where the value of the autocomplete does not have a matching …

feat(autocomplete): added new `forceFilter()` method to allow for dynamically updating the options of an autocomplete

---

src/lib/paginator/paginator-adapter.ts
src/test/spec/paginator/paginator.spec.ts

The paginator will now attempt to keep focus within itself (if it can) by explicitly moving focus to the next available focusable element when disabling the action that the user just took. For example, if clicking the "next page" button to reach the end of the data set, the focus will attempt to move to the "previous page" button. There are fall backs for each action in case the expected next action is not enabled as well to account for the various states that this component can be in.
Closes #397

fix(paginator): fixed a bug where focus was lost when disabling the page buttons dynamically

---

src/dev/pages/button-area/button-area.ejs
src/dev/pages/button-area/button-area.html
src/dev/pages/button-area/button-area.scss
src/dev/pages/button-area/button-area.ts
src/dev/src/components.json
src/lib/button-area/_mixins.scss
src/lib/button-area/button-area-adapter.ts
src/lib/button-area/button-area-constants.ts
src/lib/button-area/button-area-foundation.ts
src/lib/button-area/button-area.html
src/lib/button-area/button-area.scss
src/lib/button-area/button-area.ts
src/lib/button-area/index.ts
src/lib/index.ts
src/stories/src/components/button-area/button-area-args.ts
src/stories/src/components/button-area/button-area.mdx
src/stories/src/components/button-area/button-area.stories.tsx
src/stories/src/components/button-area/code/button-area-default.ts
src/test/spec/button-area/button-area.spec.ts

This introduces a new button area component that listens for clicks while using a visually hidden button element to accessibly enable complex and interactive nested content in clickable areas.

feat(button-area): create button area component

---

src/lib/paginator/paginator-adapter.ts
src/lib/paginator/paginator-foundation.ts
src/lib/paginator/paginator.ts
src/test/spec/paginator/paginator.spec.ts

The paginator will now allow for the `offset` value to be set **before** the `total` property. Essentially anytime the `total` property go from `0` to `>0` and there is an `offset` value applied, the `pageIndex` will now properly update.
Additionally, changes were made to how component state updates the DOM when various properties are changes to allow for fixing a bug related to how focus is managed and moved around within the component for actions triggered by user interaction vs programmatic state updates.
Fixes #400 …

fix(paginator): fixed how `offset` updates `pageIndex` along with updates to focus management

---

src/lib/field/field-foundation.ts
src/lib/floating-label/floating-label-foundation.ts
src/lib/floating-label/floating-label.ts
src/test/spec/text-field/text-field.spec.ts
src/test/utils/floating-label-utils.ts

The floating label was being reinitialized when it didn't need to be when switching between densities. This was causing the animation of the floating label to not execute. This change ensures that the floating label only reinitializes when switching between dense and non-dense densities.
A minor bug was also discovered during testing when switching to the "dense" `density` where the `<label>` element was incorrectly receiving floating label CSS classes after the `FloatingLabel` instance was destroyed (due to the …

fix(text-field): fixed a bug where the label was not being initialized properly when toggling density dynamically

---

src/lib/table/_mixins.scss
src/lib/table/table-foundation.ts
src/lib/table/table-utils.ts
src/lib/table/types.ts
src/test/spec/table/table.spec.ts

Sortable table headers will now use a `<button>` element to ensure they are part of the tab order to fix accessibility related issues to triggering sort changes on the columns via keyboard only.
Following W3 table guidance for sortable columns here:
https://www.w3.org/WAI/ARIA/apg/patterns/table/examples/sortable-table/
We should plan to introduce an API for setting the table `<caption>` as well for improved screen reader support.
Fixes #63

fix(table): sortable column headers will now use `<button>` element for a11y purposes

---

src/lib/paginator/paginator-adapter.ts
src/lib/paginator/paginator-foundation.ts
src/lib/paginator/paginator.ts
src/test/spec/paginator/paginator.spec.ts

The paginator will now manage its internal focus state in the following scenarios:
1. When state is updated that causes a button to get disabled, but only while the element is focused
2. In response to user interaction with one of the buttons that causes the button to be disabled upon clicking (again only while the field already has focus)
3. In response to a user interaction, but the state is changed from the change event listener. This is the same as the first scenario, but the order of operations is different (and …

fix(paginator): fix focus management to properly account for state updates while the element is already focused

---

src/stories/src/components/button-area/code/button-area-default.ts

- Tests for the changes have been added/updated: N/A
Fixed the expansion panel example to use correct slots

docs(button-area): add header slot to expansion panel example

---

src/dev/pages/paginator/paginator.html
src/dev/pages/paginator/paginator.ts
src/lib/paginator/paginator-constants.ts
src/lib/paginator/paginator-foundation.ts
src/lib/paginator/paginator.ts
src/stories/src/components/paginator/paginator.mdx
src/test/spec/paginator/paginator.spec.ts

Added a new `rangeLabelCallback` property that allows developers to fully customize the range label to their needs. It provides the current paginator state with pre-calculated convenience state values to allow for easy customization.
Closes #433

feat(paginator): added new `rangeLabelCallback` property to allow for controlling range label text externally

---

src/dev/pages/button/button.ejs
src/dev/pages/button/button.html
src/dev/pages/button/button.scss
src/dev/pages/button/button.ts
src/lib/button/base/base-button-adapter.ts
src/lib/button/base/base-button-foundation.ts
src/lib/button/base/base-button.test.ts
src/lib/button/base/base-button.ts
src/lib/button/button-constants.ts
src/lib/button/button-foundation.ts
src/lib/button/button.scss
src/lib/button/button.test.ts
src/lib/button/button.ts
src/lib/core/base/base-focusable-component.ts

- Added a new `full-width` attribute and corresponding `fullWidth` property to the `<forge-button>` element
- Base button will now directly use the focusable mixin instead of the facade base class for consistency
- Updated the `IBaseButton` interface to correctly inherit from `IBaseFocusableComponent` for more strict typings with symbol properties
- Fixed disabled logic to properly remove the `disabled` attribute on anchor buttons

feat(button): add full width property/attribute

---

src/lib/calendar/calendar-foundation.ts
src/lib/expansion-panel/expansion-panel-adapter.ts
src/test/spec/date-picker/date-picker.spec.ts

Removed the `aria-expanded` attribute being set on the header element when the expansion panel toggles. The header is a generic element that can't accept `aria-expanded`. This should be set on the toggling button instead, which must exist outside of the expansion panel's shadow DOM.

fix(expansion-panel): remove invalid `aria-expanded` attribute set on header

---

src/lib/date-range-picker/date-range-picker-foundation.ts
src/test/spec/date-range-picker/date-range-component-delegate.spec.ts

Updated date-range-picker initialization logic to ensure that the "to" `<input>` receives the formatted `to` date value if set by before init.

fix(date-range-picker): fixed a bug where the "to" value was not being rendered in `<input>` when initialized with a default value

---

src/lib/calendar/calendar-foundation.ts
src/test/spec/date-picker/date-picker.spec.ts

Fixes a bug where if the max date is set to a month prior to the current month, the calendar would not switch to the month of the max month. This was causing an exception to occur when trying to access a date in the incorrect month.

fix(calendar): fixed a bug where the calendar would not reflect the correct month if the max date is before the current the month

---

src/dev/pages/button/button.ejs
src/dev/pages/button/button.scss
src/dev/pages/button/button.ts
src/lib/core/styles/typography/index.scss
src/lib/deprecated/button/deprecated-button-component-delegate.ts
src/lib/deprecated/button/deprecated-button-constants.ts
src/lib/deprecated/button/deprecated-button.html
src/lib/deprecated/button/deprecated-button.scss
src/lib/deprecated/button/deprecated-button.test.ts
src/lib/deprecated/button/deprecated-button.ts
src/lib/deprecated/button/index.scss
src/lib/deprecated/button/index.ts
src/lib/deprecated/index.ts
src/lib/index.ts

This change brings support for the "decorator" pattern for buttons that we used in the 2.x version to the 3.0 version. This is only for backwards compatibility and _should_ be API-compatible with the 2.x implementation.
It allows for slotting native `<button>` elements in for backwards compatibility to ease the upgrade process:
```html
<forge-deprecated-button>
<button type="button">Decorated button</button>
</forge-deprecated-button>
```
This was ported from the 2.x version and integrated with design tokens (it uses the same styles from the new 3.0 button but with `::slotted()` selectors instead and some minor overrides to match 2.x.
This is not a direct port from 2.x and it wasn't intended to be. The styles were moved to the shadow DOM, and it was integrated with the new state-layer and …

[@next] port deprecated (2.x) button for backwards compatibility

---

src/dev/pages/banner/banner.html
src/dev/pages/banner/banner.ts
src/lib/banner/_core.scss
src/lib/banner/banner-adapter.ts
src/lib/banner/banner-constants.ts
src/lib/banner/banner-foundation.ts
src/lib/banner/banner.html
src/lib/banner/banner.scss
src/lib/banner/banner.test.ts
src/lib/banner/banner.ts
src/lib/core/styles/tokens/banner/_tokens.scss

- Added new cancelable `forge-banner-before-dismiss` event
- Updated `forge-banner-dismissed` event to dispatch after the dismiss animation is complete
- Updated theme to set icon/dismiss button color
- Fix `canDismiss` getter bug
- Update layout styles when in small container to account for no slotted button content

feat(banner): add before dismiss event and theme updates

---

src/lib/core/utils/position-utils.ts
src/lib/core/utils/utils.ts
src/lib/overlay/overlay-adapter.ts
src/lib/overlay/overlay-constants.ts
src/lib/overlay/overlay-foundation.ts
src/lib/popover/popover.test.ts
src/lib/typings.d.ts

- Adjust default configuration for flip middleware to use `document.body` as the default boundary for `:top-layer` elements
- Create map for fallback placements to use with the flip middleware that specifies specific fallbacks placements per placement
- Removed the "auto" middleware configuration. This will likely never be used.
- Default to using the "fixed" position strategy
- Always use `translate` transform for positioning instead of `top` and `left` for performance reasons

fix(overlay): update how flip positioning is handled

---

src/lib/tooltip/_core.scss

Due to our tooltips being inline in the DOM now, they can inadvertently inherit CSS styles from their ancestors. This fixes a specific issue with overflow when placed inside of an element that could potentially set something like `white-space: nowrap` but we should be aware of this potential problem for other individual style properties.

fix(tooltip): ensure `white-space` style is not inherited from ancestors to avoid overflow with wrapping text

---

src/lib/open-icon/open-icon.ts

The open icon was incorrectly auto-registering the `keyboard_arrow_left` icon for its "horizontal" orientation mode, when it actually expects to use the `keyboard_arrow_right` icon. We now correctly register the `keyboard_arrow_right` icon.
Until this is released, consumers can register the correct icon themselves if using the horizontal orientation.

fix(open-icon): auto-register correct "horizontal" icon

---

src/lib/dialog/dialog-adapter.ts
src/lib/dialog/dialog-foundation.ts

Adds logic that runs after the dialog has completed animating open to attempt to fix the ripple alignment for focusable Forge elements that use a ripple.
This fix adds some slight overhead to the dialog, but it's the most seamless way to handle it at the moment for backwards compatibility. This code does not need to migrate to 3.0 and beyond due to our separation of the focus state and interaction state.
This is a port of old logic we used to have in the 1.x version of this library. We originally removed it in 2.x …

fix(dialog): fixed a bug where opening dialogs with focused Forge elements that use the ripple could be misaligned

---

src/lib/core/base/base-adapter.ts
src/lib/list/list/list-adapter.ts
src/lib/list/list/list-constants.ts
src/lib/list/list/list-foundation.ts

`<forge-list>` elements will now ignore `keydown` events that originate from within sub-lists. This allows for each list to manage its own keyboard navigation without ancestor lists conflicting with the focus management within a specific `<forge-list>` scope/context.
Additionally, improved the detection of child `<forge-list-item>` elements by ensuring that keyboard navigation is properly scoped to the nearest `<forge-list>` parent element.
Fixes #452

fix(list): fixed a bug where keyboard navigation was not scoped within sub-lists

---

src/dev/pages/list/list.ejs
src/lib/core/styles/tokens/list/list-item/_tokens.scss
src/lib/list/list-item/_core.scss
src/lib/list/list-item/list-item-constants.ts
src/lib/list/list-item/list-item.scss
src/lib/list/list-item/list-item.ts
src/lib/list/list/list-adapter.ts
src/lib/list/list/list-constants.ts
src/lib/list/list/list-foundation.ts
src/lib/popover/popover.test.ts

- Fixed scope of keyboard navigation to ignore sub-lists
- Updated detection of list items to be properly scoped to the correct list context based on their composition (includes deeply nested list items within shadow roots)
- Updated styles to convert from using start/end `margin` on leading/trailing slotted content to instead use flexbox `gap` on the internal layout.
- Removed old margin tokens
- Added new gap tokens

fix(list): fixed keyboard navigation and used `gap` instead of `margin` for leading/trailing slots

---

src/lib/menu/menu-foundation.ts
src/test/spec/menu/menu.spec.ts

Calls the existing mapIconToLeadingIcon function when menu `options` is a `MenuOptionFactory`
Maybe a better fix would be to call the existing options setter? This was the lightest touch fix I found

fix(menu): map deprecated `icon` property to `leadingIcon` when options are loaded from factory

---

src/dev/pages/popover/popover.html
src/dev/pages/popover/popover.ts
src/lib/popover/popover-constants.ts
src/lib/popover/popover-foundation.ts
src/lib/popover/popover.test.ts
src/lib/popover/popover.ts
src/lib/tooltip/tooltip.test.ts

- Tests for the changes have been added/updated: [Y]
- Docs have been added/updated: [Y]
- I have linked any related GitHub issues to be closed when this PR is merged? [Y]
When the trigger type of the popover was set to hover, it felt like the popover was appearing too fast. Adding the delay property keeps it consistent with the tooltip, and allows us to control the speed at which the popover element appears

feat(popover): new delay property

---

src/lib/field-next/_core.scss

This fixes a problem with popovers "flipping" to opposite sides of the field based on available space in the viewport relative to the anchor element.

fix(field): updated "popover target" element styles to cover entire field container to fix anchor placement fallback positioning issues

---

src/lib/core/styles/tokens/list/list-item/_tokens.scss
src/lib/core/styles/tokens/list/list/_tokens.scss
src/lib/core/styles/tokens/popover/_tokens.scss
src/lib/list/list-item/_core.scss
src/lib/list/list-item/list-item.ts
src/lib/list/list/_core.scss
src/lib/list/list/list.html
src/lib/list/list/list.scss
src/lib/list/list/list.ts
src/lib/popover/_core.scss

- Removed the default internal `padding` in the `<forge-list>` since it should be controlled by the consumer in their own context without us making assumptions.
- Added a `spacing` token for easily adjusting the space between list items through the `<forge-list>`
- Fixed how block padding is applied when `wrap` is used on the `<forge-list-item>`
- Set `line-height: normal` on text content when `wrap` is used to ensure that wrapping text is properly spaced

fix(list): adjusted list and list-item styles to account for edge cases

---

src/lib/forge-core.scss
src/lib/utils/_mixins-core.scss

This change adjusts the `forge-core.css` stylesheet by adjusting our default styles to be more flexible, without overriding `overflow` to better support mobile usage.
- Use dynamic viewport units for `height` and `width` on the `<body>`
- Remove `overflow: hidden` on the `<body>`
- Remove applying styles on the root `<html>` element

feat(forge-core): update core styles

---

src/lib/list/list-item/list-item-adapter.ts
src/test/spec/list/list-item/list-item.spec.ts

Clicking on a list item that contains a slotted `<input type="radio">` element will no longer uncheck the radio. This is to be consistent with the native radio button functionality in the browser.
Toggling selection state of the list/list-item programmatically will still uncheck the radio. This is a synchronization of selection state rather than user interaction toggling/selecting a list item so it makes sense to ensure the radio reflects the selection state as it currently does.

fix(list-item): fixed a bug where clicking list items would uncheck slotted radio buttons

---

src/dev/pages/dialog/dialog.scss
src/lib/dialog/_core.scss
src/lib/dialog/dialog-adapter.ts
src/lib/dialog/dialog-constants.ts
src/lib/dialog/dialog-foundation.ts
src/lib/dialog/dialog.scss
src/lib/dialog/dialog.test.ts

- Using a the `visible` attribute allows us to control animations separate from the "open" state.
- React binds to attributes instead of properties, this fixes a bug where React was removing the `open` attribute immediately causing the dialog to not complete its exit animation and stay transparently in the DOM.
- Updated the default `display` style for the surface container to use the default (`block`) instead of `inline-flex` to allow for elements to be placed more naturally in the container.
- This has the drawback of the surface content not automatically expanding to fill the surface, but in these cases it's up to developers to set their own `height` which I feel is more obvious and has less drawbacks.

fix(dialog): use `visible` state attribute instead of `open` to control animations

---

src/lib/core/styles/tokens/list/list-item/_tokens.scss
src/lib/core/styles/tokens/list/list/_tokens.scss
src/lib/list/list-item/_core.scss
src/lib/list/list-item/list-item.scss
src/lib/list/list-item/list-item.ts
src/lib/list/list/list.scss

- Added default `margin-block` to `<forge-list navlist>`
- Removed "supporting" from the tokens and mixins related to the slotted text content for brevity

feat(list): add navlist block margin and tokens; rename text-related tokens in list item

---

src/dev/pages/autocomplete/autocomplete.ejs
src/dev/pages/date-range-picker/date-range-picker.ejs
src/dev/pages/keyboard-shortcut/keyboard-shortcut.ejs
src/dev/pages/time-picker/time-picker.ejs
src/dev/src/partials/controls/text-field.ejs
src/dev/src/partials/controls/time-picker.ejs
src/lib/field/field-adapter.ts
src/lib/field/field-foundation.ts
src/lib/text-field/text-field-adapter.ts
src/stories/src/components/autocomplete/autocomplete.stories.tsx
src/stories/src/components/autocomplete/code/autocomplete-default.ts
src/stories/src/components/date-picker/code/date-picker-default.ts
src/stories/src/components/date-picker/date-picker.stories.tsx
src/stories/src/components/date-range-picker/code/date-range-picker-default.ts
src/stories/src/components/date-range-picker/date-range-picker.stories.tsx
src/stories/src/components/text-field/code/text-field-default.ts
src/stories/src/components/text-field/text-field.stories.tsx
src/stories/src/components/time-picker/code/time-picker-default.ts
src/stories/src/components/time-picker/time-picker.stories.tsx
src/stories/src/mock/document-filters.tsx

The `<label>` and `<input>` elements will no longer be moved in the DOM when connected.

fix(text-field): remove legacy `<label>` & `<input>` DOM order manipulation

---

src/lib/list/list-item/list-item-foundation.ts

List items will no longer prevent default on the `mousedown` events if already focused.
This was originally in place for a legacy interaction pattern for dropdowns that is no longer necessary.

fix(list-item): removed legacy internal mousedown handler that was preventing pointer events if already focused

---

src/lib/table/table-foundation.ts
src/stories/src/components/table/table.mdx

- I have linked any related GitHub issues to be closed when this PR is merged? Fixes #557 
This was caused by the column configurations being reset and not respecting the current state of the sort direction, and instead resetting to the "initial sort" defined by the column configurations. The table will now only update the sort direction when it has not already been set.

fix(table): fixed a bug where the table sort icon rotation could get out sync

---

src/lib/list/list-item/list-item-foundation.ts
src/lib/list/list-item/list-item.ts
src/stories/src/components/list/list.mdx

A new method called `decativateRipple()` is now available on the `<forge-list-item>` elements. Developers can use this to manually remove the state layer on the ripple element.
This was added to help alleviate issues when using drag events to move elements around. The pressed state was activating on the ripple and sticking after the drag operation was completed.

feat(list-item): add `deactivateRipple()` method to allow for manually removing the "pressed" ripple state if needed

---

src/lib/select/option/option.ts
src/lib/select/select-dropdown/select-dropdown-adapter.ts
src/lib/select/select/select-adapter.ts

This is a temporary workaround to fix accessibility audits due to the dynamic nature of the dropdown in the current implementation.
A new select component is being designed for a future release that will take advantage of the new inline dropdown pattern which will properly take care of this issue and we can deprecate this legacy component at that time.

fix(select): fix missing `aria-controls` attribute to use temporary element

---

src/lib/app-bar/notification-button/app-bar-notification-button-adapter.ts
src/lib/app-bar/notification-button/app-bar-notification-button-foundation.ts
src/lib/app-bar/notification-button/app-bar-notification-button.ts
src/stories/src/components/app-bar-notifications/app-bar-notifications.mdx
src/test/spec/app-bar/notification-button/app-bar-notification-button.spec.ts

Updated the `count` property to accept more types and properly allow for disabling the count text.

fix(app-bar-notification-button): fixed a bug where the badge count could not be unset and updated the logic to not render the count

---

src/lib/menu/menu-foundation.ts
src/stories/src/components/menu/menu.mdx
src/test/spec/menu/menu.spec.ts

Pressing the `Tab` key while the menu is open will no longer select the active option.

fix(menu): fixed a bug where pressing the tab key would select the active option

---

src/lib/popover/popover-adapter.ts
src/lib/popover/popover-foundation.ts
src/lib/popover/popover.test.ts

We were previously only attempting to set focus to an element with the `autofocus` attribute if the popover was triggered via keyboard. This follows the native `popover` expectations. While it shouldn't be overused, there are a lot of design usecases that call for simple form entry in transient popovers and it's desirable to move focus immediately regardless of how the popover was triggered.
We should make a note about this in the docs regarding the accessibility caveats and how it can be confusing to screen reader users.

feat(popover): enable `autofocus` attribute when triggered via either keyboard or pointer

---

src/lib/radio/core/radio-group-manager.ts
src/lib/radio/radio-group/radio-group-adapter.ts
src/lib/radio/radio-group/radio-group-foundation.ts
src/lib/radio/radio-group/radio-group.test.ts
src/lib/radio/radio/radio-adapter.ts
src/lib/radio/radio/radio-foundation.ts
src/lib/radio/radio/radio.ts

A radio no longer sets `aria-required` on itself. Instead, when the state of `required` changes the required status of each radio in the group is evaluated and `aria-required` set on the closest `fieldset`, element with `role=radiogroup`, or `forge-radio-group`. The Forge radio group component attempts the same logic when it's added to the DOM.

fix(radio): set aria-required on radio group element instead of individual radios

---

src/dev/pages/field/field.ts
src/lib/field/_core.scss
src/lib/field/field.html

- Tests for the changes have been added/updated: N/A
- Docs have been added/updated: N/A
Fixes an issue where absolutely positioned elements of slotted content would cut off before reaching edge of the field.

fix(field): slotted elements can fill entire block size of field

---

src/lib/tabs/tab-bar/tab-bar-adapter.ts
src/lib/tabs/tab-bar/tab-bar-constants.ts
src/lib/tabs/tab-bar/tab-bar-core.ts
src/lib/tabs/tab-bar/tab-bar.html
src/lib/tabs/tab-bar/tab-bar.ts
src/lib/tabs/tabs.test.ts
src/stories/components/tabs/Tabs.stories.ts

Moves the `role="tablist"` from the `<forge-tab-bar>` to the internal scroll container element that `<forge-tab>` elements slot into. This keeps the scroll buttons outside of the tablist element.
This will fail an audit with Arc, but it's due to a bug in their audit.

fix(tab-bar): move ARIA attributes to internal scroll container for tab bar

---

.github/workflows/auto-pr-check.yml
src/dev/pages/stepper/stepper.ts
src/lib/stepper/step/step.ts

- Tests for the changes have been added/updated: n/a
Fix the event name registered to HTMLElementEventMap so that `forge-step-select` events are properly typed.
Event name is correct in Forge 3.0, though the dev page addEventListener is still incorrect.

fix(forge-step): correct select event name for proper typing

---

src/dev/pages/select/select.ejs
src/lib/button-toggle/button-toggle-group/button-toggle-group.ts
src/lib/button/base/base-button.ts
src/lib/constants.ts
src/lib/core/mixins/focus/with-focusable.ts
src/lib/core/mixins/label/with-label-aware.ts
src/lib/label/label-adapter.ts
src/lib/label/label-constants.ts
src/lib/label/label-core.ts
src/lib/label/label.test.ts
src/lib/label/label.ts
src/lib/radio/radio-group/radio-group.ts
src/lib/select/select/select-adapter.ts
src/lib/select/select/select-core.ts
src/lib/select/select/select.test.ts
src/lib/select/select/select.ts

The select component is now form associated and label aware.
Closes #635 
The label component has also been updated to connect to components that haven't yet been upgraded and ignore the text content of nested labelled components.

feat(select): native form association and label awareness

---

src/lib/app-bar/notification-button/app-bar-notification-button-foundation.ts

The `count` value will now not be displayed if in `dot` mode when a badge is visible.

fix(app-bar-notification-button): fixed a bug where the count could incorrectly display when in dot mode if not changed from default

---

src/lib/chip-field/chip-field-adapter.ts
src/lib/field/field-adapter.ts
src/lib/field/field-foundation.ts
src/lib/text-field/text-field-adapter.ts

Moves the initialization of internal element references in the shadow DOM to the constructor of the adapter to ensure that these element references are always available. This fixes a bug where an exception is thrown if the element is removed from the DOM before the element fully initializes because it waits for a child `<input>` asynchronously.

[field] fix initialization of internal element references to occur in constructor instead of connectedCallback

---

src/lib/button/_core.scss
src/lib/button/button.scss
src/lib/button/button.ts
src/lib/core/styles/tokens/button/_tokens.scss

Updated the button tokens to use variant-specific tokens for the "raised" variant instead of inheriting the "filled" tokens to reduce confusion and make it consistent with the other variants.
Additionally, fixed some CSS variable typos in the API docs.

fix(button): fix to properly wire up raised variant-specific tokens

---

src/dev/pages/icon-button/icon-button.html
src/lib/icon-button/icon-button-constants.ts
src/lib/icon-button/icon-button.test.ts
src/lib/icon-button/icon-button.ts
src/stories/components/button/Button.stories.ts
src/stories/components/icon-button/IconButton.stories.ts

The `<forge-icon-button>` previously incorrectly set its default `theme` state to "primary" which doesn't allow for the theme to be truly using the "primary" theme color for the icon like the other built-in theme colors do. This was done because by default icon buttons will use `currentColor` to inherit the color for the icon, but the state layer and focus indicator both use the primary theme.
This change will reduce confusion by setting the default state to "default" instead, which enable the "primary" theme color to …

fix(icon-button): fix to properly default `theme` to "default" to allow for "primary" to be used like other themes

---

src/lib/core/styles/tokens/list/list-item/_tokens.scss
src/lib/list/list-item/_core.scss
src/lib/list/list-item/list-item.ts

- Tests for the changes have been added/updated: N/A
A new `selected-background` token has been added that reference the `selected-color` token to allow for adjusting the background color and foreground color independently. This will help branding to ensure that these colors can easily be adjusted without `::part` selectors when overrides are needed.
During this change it was also found that the internal list item text-container was rendering below the `::before` pseudo element which was inheriting the opacity. The text-container element has now been moved to its own …

fix(list-item): separate the foreground and background selected state tokens

---

.storybook/manager-head.html
.storybook/manager.ts

Adds a temporary custom banner element to the storybook manager app at the top of the page to help users find the legacy v2.x docs more easily for the time being.
**Light theme:**
**Dark theme:**
**Mobile support:**

docs: add temporary banner with link to v2.x docs

---

src/dev/pages/table/table.ts
src/lib/core/mixins/form/with-form-associated.ts
src/lib/select/select/select.ts

This is a temporary "fix" to just omit the `disabled` property in the `WithFormAssociation` mixin until TypeScript can fix this bug in how getter accessor properties are unioned.
For now, any classes that use the `WithFormAssociation` mixin will not be required to implement the `disabled` property, but it's likely that all instance will always have that property anyway.
Here is the TypeScript issue for tracking status:
https://github.com/microsoft/TypeScript/issues/58790

fix(select): temp fix to remove disabled property from form associated mixin for TS2611 until TypeScript fixes accessor union bug

---

.eslintrc.json
package-lock.json
package.json

Fixes a compatibility issue with Windows systems via new versions of forge-cli and the underlying forge-build-tools dependencies. These packages needs to be updated to normalize file/directory paths, and this change just bumps those dependencies to fix the issue in this repo.
Additionally, the eslint config was updated to relax the line endings that are set by Prettier when run in Windows environments.

chore: fix compatibility with windows systems to use normalized file paths in CLI and build-tools deps as well as line endings in eslint

---

src/lib/badge/badge.scss
src/lib/core/styles/tokens/theme/_tokens.status.scss

Updates the `error` theme token to the `ruddy-pink-200` palette color.
Additionally, updated the badge error theme to properly use `error-container-low` for the background color to ensure passing contrast.
Fixes #648

fix(theme): use correct error theme color in dark theme

---

src/lib/core/styles/theme/_color-utils.scss
src/lib/core/styles/theme/index.scss
src/lib/core/styles/tokens/theme/_token-utils.scss
src/lib/forge-tokens.scss

The color-emphasis token values are useful for consumers to use in their applications and/or libraries to ensure seamless integration with Forge. This change emits `--forge-color-emphasis-*` CSS variables for each color-emphasis token in the `forge-tokens.css` stylesheet.

feat(tokens): include color-emphasis tokens as part of the `forge-tokens.css` stylesheet

---

src/dev/pages/dialog/dialog.ts
src/lib/dialog/dialog-adapter.ts
src/lib/dialog/dialog-constants.ts
src/lib/dialog/dialog-core.ts
src/lib/dialog/dialog.test.ts
src/lib/dialog/dialog.ts
src/stories/components/dialog/Dialog.mdx
src/stories/components/dialog/Dialog.stories.ts
src/stories/components/dialog/Dialog.ts
web-test-runner.config.mjs

Added default behavior to automatically switch the dialog to fullscreen at a specific media query breakpoint of `599px`. This breakpoint threshold can be controlled via the new `fullscreenThreshold` property/attribute if desired. Setting the threshold to a value of `0` disables this new functionality if you don't want the dialog to adjust itself automatically.
I did not use a CSS-based media query for this because the value cannot be adjusted without rewriting the CSS styles that are applied to the shadow DOM …

feat(dialog): automatically switch to fullscreen at the new `fullscreenThreshold` property value

---

src/lib/core/styles/tokens/tabs/tab/_tokens.scss
src/lib/tabs/tab/_core.scss
src/lib/tabs/tab/tab.scss
src/lib/tabs/tab/tab.ts

When rendered in small containers, or when using the `clustered` mode, tabs did not have enough space in the inline axis (horizontally by default) which caused the tab contents to be too close to each other in these scenarios. This was a regression from the 2.x to 3.0 version.
This change ensures that the default "primary" variant has `16px` of `padding-inline` set on the tab container, whereas in "secondary" mode the padding moves from the tab container to around the tab contents. This is done to ensure that the active …

fix(tab): add missing inline padding

---

src/lib/button-toggle/button-toggle-group/button-toggle-group-constants.ts
src/lib/button-toggle/button-toggle/button-toggle-constants.ts

While I would prefer to keep `unknown` since that is technically more correct, `any` is still appropriate, and it helps alleviate some friction in framework bindings such as in Angular where you cannot access the value inline due to type conflicts. This requires the use of `$any()` in some cases.

fix(button-toggle): relax the generic type on the event data interfaces to `any`

---

src/lib/checkbox/checkbox.scss
src/lib/field/_core.scss
src/lib/radio/radio/radio.scss
src/lib/switch/switch.scss

Updates various field-like components that have labels associated with their template to not apply the disabled opacity/theme to the label to ensure it is legible when disabled.

fix(checkbox, radio, switch, field): remove opacity on field labels when disabled

---

src/lib/core/styles/shape/index.scss

Updates the shape token references in all components to use a `calc()` with a new `--forge-shape-factor` multiplier token to allow for uniformly scaling the shape token values.
The utility of this is for either easily setting all `border-radius` values to `0` or to scale them up or down relative to their default value. The "full" and "round" shape tokens would likely be manually adjusted since they are kind of "presets" in a way, but they would also be affected by this.
This could be useful for branding applications …

feat(shape): enable use of `--forge-shape-factor` to uniformly control shape tokens via multiplier

---

src/lib/checkbox/checkbox-core.ts
src/lib/checkbox/checkbox.test.ts
src/lib/radio/radio/radio-core.ts
src/lib/radio/radio/radio.test.ts
src/lib/switch/switch-core.ts
src/lib/switch/switch.test.ts

Enabled handling non-string values in the checkbox, switch, and radio components at runtime to support previous unintended behavior. Strings are still expected, but in the case where non-string values are used the attribute won't be reflected.

feat: handle non-string values in checkbox, switch, and radio

---

src/dev/pages/autocomplete/autocomplete.html
src/dev/pages/autocomplete/autocomplete.ts
src/lib/list-dropdown/list-dropdown-utils.ts
src/test/spec/list-dropdown/list-dropdown.spec.ts

The `secondaryLabel` property of list dropdown options now uses the correct slot to display as it did in Forge 2.0.

fix(list-dropdown): restore display of secondaryLabel

---

src/lib/stepper/step/_core.scss

Removes the unnecessary `z-index` style from the base container element, and sets `box-sizing: border-box` to ensure that the size of the element properly accounts for its internal spacing.

fix(stepper): remove the internal `z-index` style and fix overflowing content

---

src/lib/list/list-item/_core.scss

It was found that when list items using tooltips are placed within a mini-drawer and interacted with, it causes layout calculation to be incorrect. This change forces the list item to use layout containment to ensure the descendants of the element do not affect its size incorrectly.

fix(list-item): use `layout` containment on the text-container part to ensure that slotted elements (specifically tooltips) do no affect the layout

---

src/lib/core/utils/date-utils.ts
src/lib/date-picker/date-picker-core.ts
src/lib/date-range-picker/date-range-picker-core.ts
src/test/spec/date-picker/date-picker.spec.ts
src/test/spec/date-range-picker/date-range-picker.spec.ts

The date-picker and date-range-picker were incorrectly clearing out the timestamp portion of the provided `Date` object(s) when performing a date comparison for equality. This was causing issues when developers were loading dates that have timestamps but the component was removing that timestamp silently without the field being interacted with.
This change ensures that the date comparison does not adjust the `Date` objects, and also the timestamp is preserved when the user chooses a date from the dropdown calendar.
The …

fix(date-picker): ensure that time portion of `Date` value is preserved during initial render and dropdown calendar selection

---

src/dev/pages/list/list.scss
src/lib/list-dropdown/list-dropdown-utils.ts
src/lib/list/list-item/list-item-constants.ts
src/lib/list/list-item/list-item-core.ts
src/lib/list/list-item/list-item.ts

- I have linked any related GitHub issues to be closed when this PR is merged?N
Adds new `allowFocusPropagation` configuration to the `<forge-list-item>` element to allow for controlling whether focus is propagated to the interactive element or not (`true` by default).
This is used within the list-dropdown to ensure that when the user interactive with a non-interactive element in a list item within the dropdown (which should never receive focus) that the interactive element doesn't inadvertently get focused. When used statically within a page, list items should always propagate focus.

fix(list-item): fixed a bug where focus was being forced to propagate to the interactive element when used within a list dropdown

---

src/lib/chips/chip/chip-core.ts
src/lib/chips/chips.test.ts

The `forge-chip` element will no longer sync `value` property changes back to the attribute, as this caused the `attributeChangedCallback` to run and overwrite non-string values to string values, which is problematic if the value was numeric or an object.  The `value` will continue to initialize/update the property, but changes will not be reflected back.  This is consistent with Forge 2.0, and also the checkbox/switch/radio components.

fix(chip): remove attribute syncing to prevent value being forced to string

---

src/lib/chip-field/chip-field.scss
src/lib/chips/chip/chip.scss
src/lib/chips/chip/chip.ts
src/lib/core/styles/tokens/chips/chip/_tokens.scss

Adds a new `--forge-chip-focus-indicator-color` token to the `<forge-chip>` to allow for separating the focus indicator color from the chip text color. This fixes an issue with the chip-field when the chip-field `theme` attribute is applied to ensure that the focus indicator is always using the provided theme color.

fix(chip-field): add `focus-indicator-color` token to chips to fix themed "field" chips

---

src/lib/circular-progress/_core.scss

The host element styles will now use `block-size` and `inline-size` to set an explicit size instead of `min-block-size` and `min-inline-size` to avoid cases where flex layouts could inadvertently take control of the element dimensions.

fix(circular-progress): updated the host element to set `block-size` and `inline-size` explicitly

---

src/dev/pages/paginator/paginator.ejs
src/lib/paginator/paginator.html

Ensures that the `<forge-popover>` element for the rows per page select is appended within the shadow root of the paginator to allow for IDREF attributes to reference the correct elements in the dynamic dropdown.
Fixes #715

fix(paginator): append select popover to shadow root to attach IDREFs

---

src/lib/button/base/base-button-adapter.ts

Calling `click()` on any element that derives from the base button before the element is connected to the DOM would result in an exception relating to the state-layer `playAnimation()` method. This change ensures that the state layer is connected to the DOM before attempting to run its visual animation-related logic in response to a click event.

fix(base-button): fixed a bug where calling `.click()` on a button before it's connected would result in an exception

---

src/dev/pages/skip-link/skip-link.html
src/dev/pages/skip-link/skip-link.ts
src/lib/skip-link/skip-link-constants.ts
src/lib/skip-link/skip-link.test.ts
src/lib/skip-link/skip-link.ts
src/stories/components/skip-link/SkipLink.stories.ts

This adds an alternative navigation method to the skip link for usage in contexts that don't allow navigation by URL fragment. When `skip-url-change` is set URL navigation is canceled and the target element is instead focused and scrolled into view via JavaScript.

fix(skip-link): allow focusing without url navigation

---

src/lib/autocomplete/autocomplete-adapter.ts
src/test/spec/autocomplete/autocomplete.spec.ts

Fixes #682
The `forge-popover-toggle` event is raised from the `forge-popup` host element, but the autocomplete was listening for the event on its `anchorElement`, so when dismissed via clicking on the input (or anywhere in the anchor) it was not properly reflecting the open state of the dropdown.

fix(autocomplete): properly reflect dropdown open state if dismissed by anchor click

---

src/lib/field/_core.scss
src/lib/field/_core.theme.scss
src/lib/field/field.scss
src/lib/field/forge-field.scss

This fixes an issue where the outline of certain field variants wasn't encompassed by the field's box, leading to situations where the outline could overflow or overlap other elements. Margin or padding equal to the outline's width has been added to account for this.
**Update**: Refactored to move the outline inward instead of adding margin or padding.

fix(field): extend box to include outline

---

src/lib/field/field-adapter.ts
src/lib/field/field-core.ts
src/lib/select/select/select.html
src/lib/text-field/text-field-adapter.ts
src/lib/text-field/text-field-constants.ts
src/lib/text-field/text-field-core.ts

In a rare edge case if fields are added to the DOM before the `slotchange` event listener runs, the internal state for inset (floating) labels would not initialize properly. This change adds an explicit detection step when connecting to the DOM to ensure that this DOM state is properly captured on initialization and when slotted content changes.
This was found (and only reproducible) in an Angular component where content projection and conditional `<ng-content>` elements were used together. This resulted in a timing edge …

fix(field): fixed a rare bug where the inset label state was not initializing properly based on the existence of slotted content

---

src/lib/tabs/tab-bar/tab-bar-core.ts
src/lib/tabs/tab-bar/tab-bar.ts
src/lib/tabs/tab/tab-constants.ts
src/lib/tabs/tab/tab.ts
src/lib/tabs/tabs.test.ts

Fixes #707
Initially and when new tabs are added to the DOM, only override their disabled state if the tab-bar is disabled, otherwise respect the disabled state of the tabs itself.
Setting the disabled property of the tab-bar will still override the disabled state of all child tabs.  Documentation has been updated to indicate that mixing the two methods of disabling tabs is not supported.  In scenarios where tabs are always enabled/disabled as a group, the developer has the option of setting tab-bar disabled as a …

fix(tab-bar): allow individually disabled tabs with enabled tab-bar

---

src/dev/pages/button/button.ejs
src/dev/pages/button/button.scss
src/dev/src/styles/_flex.scss
src/lib/button/_core.scss
src/lib/button/button.scss
src/lib/button/button.ts
src/lib/button/forge-button.scss
src/lib/core/styles/tokens/button/_tokens.scss

All non-text and non-link variants will now use the correct `padding-inline` value.
Additionally, included a change to `vertical-align` on the host element to ensure that inline buttons next to each other are aligned properly.

fix(button): fixed inline padding on all non-text variants

---

src/lib/dialog/_animations.scss
src/lib/dialog/build.json
src/lib/dialog/dialog.scss

The `forge-dialog.scss` file was not being built and distributed with the npm package. This change ensures that happens, as well as updated the animation names to be prefixed for when they are potentially loaded on the page globally to avoid conflicts.

fix(dialog): expose CSS-only stylesheet

---

src/lib/app-bar/search/app-bar-search-adapter.ts
src/lib/app-bar/search/app-bar-search.html
src/lib/autocomplete/autocomplete-adapter.ts
src/lib/autocomplete/autocomplete-core.ts
src/lib/list-dropdown/list-dropdown-utils.ts
src/lib/popover/popover-core.ts

There are 3 bugs fixed in this PR, and they are all related so I chose to keep them together in a single PR:
1. `ListDropdown`: The resulting `<forge-popover>` will now use `triggerType = 'manual'` to avoid click event conflicts with the anchor element when the popover is "anchored" to a different element than the element it listens for interactions on. All components that utilize the `ListDropdown` already handle their own interaction events anyway, so this just required a small tweak to the autocomplete to ensure it …

fix: fixed a composition/initialization bug for `<forge-autocomplete>` and `<forge-app-bar-search>`

---

src/lib/field/_core.theme.scss
src/lib/field/field.scss

Fixes a regression where support text wasn't changing to the error color when a field is invalid.

fix(field): use error color for support text when field is invalid

---

src/lib/chip-field/chip-field-adapter.ts
src/lib/chip-field/chip-field-core.ts

Updates the `<forge-chip-field>` to ignore click events that original from its child `<input>` element. This was unnecessary to begin with, but it was also causing conflicts with `<forge-autocomplete>` where the dropdown was opening and immediately closing due to both elements responding to the same click event in succession.
Fixes #735 caused by a regression recently in #725

fix(chip-field): fixed a bug where the dropdown would close immediately if clicking directly on the `<input>` element

---

.storybook/preview.ts
src/stories/faq/FocusIndicatorClipping.mdx
src/stories/faq/FocusIndicatorClipping.stories.ts

Added a new top-level "FAQ" section to the sidenav, which includes a new dedicated docs page that describes how to handle focus indicator clipping.
This is related to and depends on the changes in #736

docs(FAQ): added a new FAQ page describing how to handle focus indicator clipping

---

src/lib/text-field/text-field-component-delegate.ts

No longer sets an `id` on the `<forge-text-field>` element, only on the `<input>` and `<label>` elements.
Fixes #729

fix(TextFieldComponentDelegate): fix duplicate `id` being set when provided via options

---

src/lib/field/field.scss

Visually hides the `::before` pseudo element at the "extra-small" density.
Fixes #728

fix(field): hide required asterisk at extra-small density

---

src/lib/field/field-adapter.ts
src/lib/field/field-constants.ts

When fields (text-fields for example) are used within layouts that collapse their content, such as flexbox, the field width could collapse down to the min content width while the inset/floating label animation is executing. This change ensures that the internal input container locks its width to the current width before the animation begins to avoid the collapse, and then removes the locked width after the animation completes.
Given that this is only temporary while the animation executes, and there is no reliable …

fix(field): fixed a bug where the width could collapse while the inset label animation is executing

---

src/lib/core/styles/tokens/card/_tokens.scss
src/lib/core/styles/tokens/scaffold/_tokens.scss
src/lib/expansion-panel/_core.scss
src/lib/expansion-panel/expansion-panel-adapter.ts
src/lib/expansion-panel/expansion-panel-constants.ts
src/lib/expansion-panel/expansion-panel-core.ts
src/lib/expansion-panel/expansion-panel.scss
src/lib/expansion-panel/forge-expansion-panel.scss
src/lib/scaffold/_core.scss
src/lib/scaffold/forge-scaffold.scss

Updates the card, scaffold, and expansion panel internal `overflow` styles to default to `initial` (or `visible` by default) instead of `hidden`.
This allows for content nested within to properly overflow its bounds for things like focus indicators.
This change _could_ potentially cause inadvertent overflow in specific layouts that rely on it, but in initial testing this would likely be pretty rare, and it is much more likely (and predictable) that developers want overflow by default and instead manually set `hidden` if …

fix: allow overflowing content in card, scaffold, and expansion panel

---

src/lib/accordion/accordion-constants.ts
src/lib/accordion/accordion-core.ts
src/lib/accordion/accordion.test.ts
src/lib/accordion/accordion.ts
src/lib/expansion-panel/expansion-panel-constants.ts
src/lib/expansion-panel/expansion-panel-core.ts
src/lib/expansion-panel/expansion-panel.test.ts
src/lib/expansion-panel/expansion-panel.ts

Previously when a user toggled a `<forge-expansion-panel>` element via the UI, any other open panels that are closing in response to that interaction would not dispatch their `forge-expansion-panel-toggle` event.
This was problematic when code is bound to each panel that needs to be updated based on the open state of that panel, so there was not way for that code to be autonomous in response to the users toggling other panels.
This change uses a new internal API (via `Symbol` property) to allow for the …

fix(accordion): always dispatch `forge-expansion-panel-toggle` event on panels that are closing in response to a user toggling another panel

---

src/lib/list-dropdown/list-dropdown-adapter.ts
src/lib/overlay/overlay-adapter.ts
src/lib/overlay/overlay-constants.ts
src/lib/popover/popover.scss

This change adds some post-positioning logic to the overlay that handles positional adjustments if the overlay contents are clipped by the viewport in either the x or y axis. The popover itself will now apply styles to itself based on this clipping state as well to ensure that the content can gracefully handle small containers/viewports by scrolling the content.

fix(popover): gracefully handle how popovers are positioned when their dimensions are clipped by the viewport to ensure access to the content

---

src/lib/field/field-adapter.ts
src/lib/field/field-constants.ts
src/lib/field/field-core.ts
src/lib/field/field.test.ts

The floating label animation does not need to execute if there are no slotted nodes in the `label` slot of a field. This change ensures that the floating label animation logic is skipped if there are no label elements to animate.
This fixes an issue where the `width` style would get orphaned on the input container element causing the clear button that is dynamically appended to inadvertently get pushed out of view.

fix(text-field): fixed a bug where the input container would lock its width if there is no floating label to animate

---

src/lib/field/field.html

Adds `aria-hidden="true"` to the internal `<svg>` element that renders the built-in "popover icon" within the `<forge-field>` to ensure that it is not read by assistive technology.
This was being flagged by Level Access.

fix(field): set `aria-hidden="true"` on popover icon `<svg>`

---

src/lib/autocomplete/autocomplete-adapter.ts
src/lib/field/field-adapter.ts
src/lib/field/field-constants.ts
src/lib/field/field-core.ts
src/lib/field/field.test.ts
src/lib/field/field.ts
src/test/spec/autocomplete/autocomplete.spec.ts

Fixes issue where autocomplete with text-field + popoverIcon (but not chip-field) would currently have issues with the dropdown when the icon was clicked directly:

fix(autocomplete): preventDefault on popover-icon mousedown instead of click

---

src/lib/time-picker/time-picker-adapter.ts
src/lib/time-picker/time-picker-core.ts

The input element reference can technically be undefined from a typings perspective. This change adds `undefined` to the type to ensure that code relying the input can handle it potentially not being set.
This can happen if the element is added to the DOM, but quickly removed before it had a chance to initialize and attach itself to a child input element, which can happen in incremental rendering situations.

fix(time-picker): gracefully handle input element reference being undefined

---

src/lib/calendar/calendar-dropdown/calendar-dropdown.ts
src/lib/popover/popover-adapter.ts
src/lib/time-picker/time-picker-adapter.ts

This change introduces a check for surface element visibility before attempting to run the exit animation, if the element is not visible at this time, then it will immediately close without an animation.
This fixes a bug where the `animationend` listener would not execute because the browser has CSS applied that is hiding the element which means CSS animations do not run.
Fixes #755

fix(popover): fixed a bug where the popover would stay connected if hidden at time of exit animation

---

src/dev/pages/text-field/text-field.ts
src/lib/field/_core.animation.scss
src/lib/field/_core.layout.scss
src/lib/field/_core.slotted.scss
src/lib/field/field-adapter.ts
src/lib/field/field.scss
src/lib/field/field.test.ts

This change removes the internal `width` being set while the inset floating label animation is running, but instead switches the `<input>` styles to use a simpler `padding-block-start` transition. This ensures that the input container doesn't use `position: absolute` any longer, but does come with the caveat of animating padding which is less performant.
Fixes #752

fix(field): fix input size/animation when floating label with inset variant

---

src/lib/select/core/base-select-adapter.ts
src/test/spec/select/select.spec.ts

- Tests for the changes have been added/updated: No
- Does this PR introduce a breaking change? No
- I have linked any related GitHub issues to be closed when this PR is merged? No
When creating a select element, passing in options that have elementAttributes will now apply those attributes to the select options.
Kieran was going to look at at a test for this.
I also linked the issue to a separate PR for v3

fix(select): elementAttributes are now applied to select options

---

src/lib/calendar/calendar-core.ts
src/lib/core/styles/tokens/icon-button/_tokens.scss
src/lib/icon-button/_core.scss
src/lib/icon-button/icon-button.ts
src/stories/components/icon-button/IconButton.mdx
src/stories/components/icon-button/IconButton.stories.ts
src/test/spec/date-picker/date-picker.spec.ts

The default/"icon" variant will now have a background color when toggled to the "on" state. This is consistent with the rest of the variants, and offers additional emphasis when the toggle state is changed. Another reason for this change is due to using the same icon in both "on" and "off" states without there being enough visual emphasis in this variant.
Also, added new demo and supporting docs for the toggle mode.

[icon-button] improve docs for toggle mode + background color for "icon" variant when toggled on

---

src/lib/popover/popover-adapter.ts

Adds an animation frame delay to ensure styles are updated prior to checking surface visibility.
Fixes #755 for Firefox compatibility

fix(popover): delay visibility check when hiding by a frame to ensure style calculation has enough time to execute

---

src/dev/pages/typography/typography.ejs
src/lib/core/styles/tokens/typography/_tokens.label.scss
src/stories/design-tokens/Typography.mdx
src/stories/getting-started/Typography.mdx

Per discussion with the governance committee about #769 it was also decided that we should introduce a new label typography style called `label3` that uses a `14px` font size.
Currently this type style is unused within the library itself, but may be valuable for design purposes in the future.

feat(typography): add new `label3` style

---

src/dev/pages/tabs/tabs.ejs
src/dev/pages/tabs/tabs.html
src/dev/pages/tabs/tabs.ts
src/lib/core/styles/tokens/tabs/tab/_tokens.scss
src/lib/tabs/tab-bar/_core.scss
src/lib/tabs/tab-bar/tab-bar-core.ts
src/lib/tabs/tab-bar/tab-bar.ts
src/lib/tabs/tab/_core.scss
src/lib/tabs/tab/tab-adapter.ts
src/lib/tabs/tab/tab-core.ts
src/lib/tabs/tab/tab.scss
src/lib/tabs/tab/tab.ts
src/lib/tabs/tabs.test.ts
src/stories/components/tabs/Tabs.mdx
src/stories/components/tabs/Tabs.stories.ts

- Does this PR introduce a breaking change? N (`secondary` APIs exist, but have no effect)
After discussion with the Forge design governance committee, it was determined that we should combine the "primary" (default) and "secondary" variants into a single design. This is purely related to the indicator, and the new (and only) default design can be seen below.
The `secondary` property and attribute still exist, as well as any related design tokens, but they have no effect on the design. I've marked them as deprecated. It was done this way to avoid breaking any …

feat(tabs): deprecate `secondary` prop/attr and update default design to use full width tab indicator

---

src/dev/pages/checkbox/checkbox.ejs
src/dev/pages/radio/radio.ejs
src/dev/pages/switch/switch.ejs
src/lib/checkbox/_core.scss
src/lib/radio/radio/_core.scss
src/lib/switch/_core.scss
src/stories/components/checkbox/Checkbox.stories.ts
src/stories/components/radio/Radio.stories.ts
src/stories/components/switch/Switch.stories.ts

The checkbox, radio, and switch will now use the larger `label2` typography style. This is an increase from `12px` to `13px` which is considered to be more readable in terms of accessibility.

fix: update checkbox, radio, switch label typography to use `label2` (13px) typography by default

---

src/lib/text-field/text-field.ts

Add missing call to `disconnectedCallback()` to ensure that cleanup logic properly runs when the element is removed from the DOM.

fix(text-field): ensure cleanup logic runs when element is disconnected

---

src/lib/text-field/text-field-core.ts
src/lib/text-field/text-field.test.ts

The inset floating label will now float properly when invalid characters are entered in `<input type="number">` fields.
The characters themselves can technically be valid numbers such as "e", ".", "+", "-" but number inputs in browsers will often see characters such as "e" as bad/invalid input and therefore the `value` property doesn't reflect the visual value as a valid number. This was causing the label to not float in this scenario.
This change adds a special case to force the floating label state if these types of …

fix(text-field): label will now float when invalid chars are entered in number inputs

---

src/lib/drawer/base/_mixins.scss
src/lib/drawer/drawer/drawer.scss

A recent Safari update broke an `@supports` selector that was previously being used to fix a repaint problem occurring in Safari after the drawer open animation completes. This selector has been fixed to always apply now.
Included an additional adjustment to switch from flex to grid for the drawer host element to ensure that the container element properly fills the available space by default.

fix(drawer): fixed a bug where the drawer would not repaint after transitioning in Safari

---

.eslintrc.json

These eslint rules were overrides that we previously had in place on this repo until they were pushed into the shared eslint rules package, they were just never removed from this repo when we upgraded the dependency...

chore(eslint): remove duplicate eslint rules

---

src/lib/avatar/_core.scss
src/lib/backdrop/_core.scss
src/lib/divider/_core.scss
src/lib/linear-progress/_core.scss
src/lib/split-view/split-view-panel/_mixins.scss
src/lib/split-view/split-view/_mixins.scss
src/lib/toolbar/_core.scss

The `contain` CSS style should be used in specific cases where it either improves performance or can fix a specific problem.
There were a few usages of this style across the library that were added as pre-optimizations and this PR removes those.
This will also fix a couple bugs related to the backdrop and split view components when used in layouts where layout shifts occur.
Fixes #783

fix: reduce usage of `contain` style to only required instances

---

src/lib/split-view/split-view-panel/_mixins.scss

Fixed a bug caused by the v2 to v3 migration to Sass modules where `unique-id` from the `sass:string` module was not being called, which caused the panel keyframes animation to be incorrect.

fix(split-view-panel): fixed a bug relating to the open animation direction

---

src/stories/components/button-area/ButtonArea.stories.ts

- Tests for the changes have been added/updated: N/A
Added a slotted `<button>` element to the button area demo. This is required to use the button area correctly but was missing before.

docs(button-area): add required slotted button to demo

---

src/lib/core/styles/tokens/app-bar/search/_tokens.scss

Increased the placeholder color emphasis (opacity) to the "higher" token (70%) to fix color contrast on top of the semi-opaque background color applied to the background of container.
Old (not passing):
New (passing):
Fixes #796

fix(app-bar-search): fixed a color contrast issue by increasing the color emphasis on the placeholder text due to the transparent background

---

src/lib/file-picker/file-picker-adapter.ts
src/lib/file-picker/file-picker-core.ts

The file picker creates a callback in its constructor that holds a reference to its `<input>`, but does not release resources when the element is disconnected. This change will just ensure that the callback is reset to `undefined` when the element is disconnected to ensure resources can be released.

fix(file-picker): cleanup callback to avoid reference being held which can leak

---

src/lib/label-value/_core.scss

Adds `overflow-wrap: anywhere` to the label and value container elements to automatically break long words when wrapping to avoid overflowing content.

fix(label-value): allow for content to wrap long words without overflowing

---

package-lock.json
package.json
src/lib/list/list-item/_core.scss

Fixes a layering problem where the selected state overlay in the list item (using the `::before` pseudo element) was covering the slotted elements causing issues with pointer events and tooltips.
This change makes sure the slotted elements are rendered above that overlay in their own stacking context, and disable pointer events on the overlay itself.

fix(list-item): fixed a bug where the selected state overlay could render on top of slotted elements

---

src/lib/index.ts

An exception was occurring at runtime when using the `defineComponents()` helper function due to the newly added Lit-based components being incompatible with the internal `defineCustomElements()` helper function from `@tylertech/forge-core` (which expects certain the tag name to exist on the element class prototype that does not exist on the Lit-based classes).
This change swaps from using the `defineCustomElements()` helper function to just importing and calling the individual component-specific definition functions …

fix(defineComponents): fixed an exception caused by lit-based components being incompatible with internal Forge API during element definition

---

src/lib/table/table-utils.ts
src/test/spec/table/table.spec.ts

- Tests for the changes have been added/updated: [Y]
- Docs have been added/updated: [N]
The forge-table automatically adds an aria-hidden to any header cell that's empty. The problem was, the aria-hidden was being added to table headers that used a custom headerTemplate as well. If someone is using a custom headerTemplate we don't want to automatically assume it needs to be hidden from assistive technology, we'll leave that up to the consumer

fix(table): only apply `aria-hidden` on `<th>` elements if `headerTemplate` is not used

---

web-test-runner.config.mjs

Added `filterBrowserLogs` to WTR config to remove Lit dev mode logs from output.

chore(test): filter Lit dev mode warning from test output

---

src/lib/tabs/tab-bar/tab-bar-adapter.ts
src/lib/tabs/tab-bar/tab-bar-constants.ts
src/lib/tabs/tab-bar/tab-bar-core.ts
src/lib/tabs/tab-bar/tab-bar.html
src/lib/tabs/tab-bar/tab-bar.ts
src/lib/tabs/tabs.test.ts

- Does this PR introduce a breaking change? Partially, the `data-aria-label` attribute no longer has any effect but won't break code.
This change moves the `tablist` role from the internal container element to the host element to ensure that developers can supply their own necessary ARIA attributes directly, while also allowing audit and scanning tools to properly test for the tablist and tab composition.
The custom `data-aria-label` attribute that was previously available on the component as an attribute only has been removed and developers can now just use …

fix(toolbar): move internal `tablist` role to host element

---

src/lib/checkbox/_core.scss
src/lib/checkbox/checkbox.ts
src/lib/core/styles/tokens/checkbox/_tokens.scss
src/lib/core/styles/tokens/radio/_tokens.scss
src/lib/core/styles/tokens/switch/_tokens.scss
src/lib/radio/radio/_core.scss
src/lib/radio/radio/radio.ts
src/lib/switch/_core.scss
src/lib/switch/switch.ts

Exposed `align` token similar to how we expose `justify` already to allow for devs to control the checkbox position when long/wrapping labels are used.
Additionally, fixed a layout bug where `flex-shrink` was use on the root flex container when instead it should be applied to the checkbox container element (flex item) instead to avoid reducing the checkbox size in small containers with wrapping label text.

fix: exposed `align` token and fixed layout bug with long labels for checkbox, radio, and switch

---

src/lib/button-area/_core.scss

- I have linked any related GitHub issues to be closed when this PR is merged? &
Set `block-size` and `inline-size` of the root element to 100% to force it to match the dimensions of the host element.
Fixes #808

fix(button-area): force root element to match size of host

---

src/lib/button/base/base-button-adapter.ts
src/lib/tabs/tab-bar/tab-bar-adapter.ts
src/lib/tabs/tab-bar/tab-bar-core.ts
src/lib/tabs/tabs.test.ts

The tab bar was setting focus to tabs when the `activeTab` property was being set, which is incorrect. We should only be setting focus if the tab was activated in response to a user interacting with the tab via mouse or keyboard.
Developers can now choose to set focus manually if they need to when switching the active tab.

fix(tab-bar): setting `activeTab` property will no longer focus the tab

---

src/dev/pages/dialog/dialog-template-basic.ejs
src/dev/pages/dialog/dialog.ejs
src/lib/dialog/dialog-adapter.ts
src/lib/dialog/dialog-constants.ts
src/lib/dialog/dialog-core.ts
src/lib/dialog/dialog.scss
src/lib/dialog/dialog.test.ts
src/lib/dialog/dialog.ts
src/stories/components/dialog/Dialog.mdx
src/stories/components/dialog/Dialog.stories.ts
src/stories/components/dialog/Dialog.ts

- Does this PR introduce a breaking change? Partially, but is required to allow for proper accessibility (won't break code).
The current state of the `<forge-dialog>` is not accessible in that it doesn't announce the dialog label and description unless an element is focused within the native `<dialog>`. Also, this presents a situation where we semantically had two `dialog` roles in the DOM at the same time, but the native `<dialog>` was making the `<forge-dialog role="dialog">` inert (removing it from the accessibility tree). This was also causing auditing tools …

feat(dialog): adjust default a11y semantics and add new `label` and `description` APIs for providing ARIA info

---

src/dev/pages/switch/switch.ejs
src/dev/src/partials/controls/switch.ejs
src/lib/switch/switch-adapter.ts
src/lib/switch/switch-component-delegate.ts
src/lib/switch/switch-constants.ts
src/lib/switch/switch-core.ts
src/lib/switch/switch.test.ts
src/lib/switch/switch.ts
src/stories/components/switch/Switch.mdx
src/stories/components/switch/Switch.stories.ts

The switch currently supports a legacy `selected` property and a new `on` property that are aliases of each other. When we started Forge v3 we introduce `on` thinking it would give more semantic meaning, but we've learned that frameworks such as Angular do not place nice with this naming, and since then the spec moved forward with a built-in switch based using an `<input>` and this uses `checked`.
We are going to now deprecate the `on` property in favor of `checked` and this PR addresses those changes.

feat(switch): add new `checked` property/attribute and deprecate `on` property

---

src/dev/pages/switch/switch.ejs
src/lib/icon-button/icon-button-constants.ts
src/lib/icon-button/icon-button-core.ts
src/lib/icon-button/icon-button.scss
src/lib/icon-button/icon-button.test.ts
src/lib/icon-button/icon-button.ts
src/lib/switch/switch.scss
src/stories/components/icon-button/IconButton.stories.ts

The icon-button currently supports an `on` property, and when we started Forge v3 we introduced `on` instead of `isOn` from v2 thinking it would give more semantic meaning and consistency, but we've learned that frameworks such as Angular do not place nice with this naming...
We are going to now deprecate the `on` property in favor of `pressed` (which mimics the `aria-pressed` state) and this PR addresses that change.

feat(icon-button): add new `pressed` property/attribute and deprecate `on` property

---

src/lib/dialog/dialog-adapter.ts
src/lib/dialog/dialog-constants.ts
src/lib/dialog/dialog.test.ts

A bug was found where changing the `label` or `description` property/attribute would cause multiple visually hidden accessibility-related elements to show up in the DOM. This just cleans that up to ensure the elements are reused/removed properly when the values change.

fix(dialog): reuse internal accessible elements if `label` or `description` change dynamically

---

src/lib/autocomplete/autocomplete-adapter.ts

A regression was found between v2 and v3 where the autocomplete will no longer traverse composed `<slot>` attributes for the `<input>` element. This change reintroduces our custom utility `deepQuerySelectorAll()` which will handle the composition properly.

fix(autocomplete): traverse composed slots when locating input element

---

src/lib/dialog/dialog-adapter.ts
src/lib/dialog/dialog-core.ts

This PR contains a fix for a bug in Chrome where where pressing the escape key twice in succession would always close the native `<dialog>` because you can't prevent default on the `cancel` event multiple times... This is seen as a bug by the community but Chrome has said that it is not. The workaround is to just use a `keydown` listener on the window and prevent default when the escape key is pressed, and this works across all browsers but is unfortunate.
The second fix included with this PR is the teardown logic for …

fix(dialog): fixed escape key bug when persistent and improved destroy logic

---

src/lib/core/utils/utils.ts
src/lib/text-field/text-field-core.ts

The`_onValueChange()` method was overloaded for two different types of listeners that provide arguments with different types (`InputEvent` or `string | null`). This method was not properly typed to allow for this overload, and therefore caused a regression when #778 was introduced.
This PR separates these listeners to be more explicit about what type of change they are handling, as well as introduces a safety check for the `InputEvent` type to be even more explicit about the fix for #778.

fix(text-field): fixed a bug where the internal value change listener was not safely guarding types

---

src/lib/field/field.scss

Changed the CSS selector for the hover state to use `:hover` on the container element instead of the host.
Fixes #839

fix(field): only apply hover state when cursor is over container

---

package-lock.json
package.json
src/lib/dialog/dialog-adapter.ts
src/lib/dialog/dialog-constants.ts
src/lib/dialog/dialog-core.ts
src/lib/dialog/dialog.test.ts
src/lib/dialog/dialog.ts
web-test-runner.config.mjs

Currently the `<forge-dialog>` captures and sets focus on the native `<dialog>` internally, and then will also check for an `autofocus` attribute and attempt to set focus to an element with that attribute. This works great and is expected for modal dialogs, but for non-modal dialogs it can be problematic moving focus automatically which could be unexpected.
This change will now only set focus to the `<dialog>` element if it is modal. The inline-modal and nonmodal modes will not do this by default. The `autofocus` …

fix(dialog): only force-capture focus when modal

---

src/lib/time-picker/time-picker-adapter.ts

Remove extra margin-right that was applied to the popover icon in this component but no other field components.
Fixes #852

fix(time-picker): remove extra icon margin

---

src/lib/select/select/select-core.ts
src/lib/select/select/select.test.ts

Fixes #847 
This was an oversight, probably caused from the migration from v2 to v3 where an if statement was blocking the label float logic if the dropdown was open. Simply removing the if statement fixes the issue so that it can attempt to float the label regardless of the open state.

fix(select): fixed a bug where the inset label would not float if the value was set while the dropdown is open

---

src/stories/components/menu/Menu.mdx
src/stories/components/menu/Menu.stories.ts

Adds documentation of grouped options to `Menu`.  This functionality was existing, but was not documented on storybook

docs: add support for grouped menu options in documentation and stories

---

src/lib/field/_core.scss

This fixes field components to use `auto` for the enabled cursor instead of `unset`. `unset` was causing slotted `<input>` elements to inherit their parent's cursor style, i.e. the default pointer, when they should use the text cursor.

fix(field): ensure that enabled field inputs use the text cursor

---

src/dev/pages/menu/menu.ts
src/dev/src/partials/options-drawer.ejs
src/dev/src/styles/_options.scss
src/lib/list-dropdown/list-dropdown-constants.ts
src/lib/list-dropdown/list-dropdown-utils.ts
src/lib/menu/menu-constants.ts
src/lib/menu/menu-core.ts
src/lib/menu/menu.ts
src/lib/select/core/base-select-adapter.ts
src/lib/select/option/option-constants.ts
src/lib/select/option/option-core.ts
src/lib/select/option/option.ts
src/lib/switch/switch.ts

Adds support for tooltip configuration to menu options (and other list dropdown-based components). This will allow developers to add tooltips to options via the `options` property on a menu.
```javascript
const options = [
{ label: 'Option', value: 'some-value', tooltip: { text: "My tooltip" } }
];
```

feat(menu): added support for option tooltips

---

src/lib/field/field.scss

The required asterisk will no longer apply to the internal label container element if there is no `<label>` element slotted.

fix(field): do not show required asterisk if no label is present

---

src/lib/list/list-item/_core.scss
src/lib/list/list-item/list-item.scss

Ensure that the slotted `<button>` elements are properly styled to fill the available space to handle content overflowing, ellipseing, and wrapping.

fix(list-item): improve overflow handling on slotted `<button>` elements

---

src/lib/tabs/tab-bar/tab-bar-core.ts
src/lib/tabs/tabs.test.ts

Added a call to the internal scroll button detection logic whenever the default slot changes.

fix(tabs): fixed a bug where the scroll buttons were not being shown/hidden when tabs are dynamically added/removed

---

src/lib/field/base/base-field.ts
src/lib/field/field-constants.ts
src/lib/field/field.html
src/lib/field/field.ts
src/lib/select/select/select.ts
src/lib/text-field/text-field.ts

- https://github.com/tyler-technologies-oss/forge/issues/845
The `class="outline"` element of the forge-field is exposed as a CSS part.

feat(field): expose `class="outline"` element as a CSS part

---

src/lib/core/utils/a11y-utils.ts
src/lib/core/utils/utils.ts
src/lib/meter/meter-group/meter-group.ts
src/lib/meter/meter/meter.ts

Exposes the `toggleState()` helper and moves it from a11y-utils to generic utils.

chore: move `toggleState()` helper to general utils and export from lib

---

src/lib/avatar/avatar.test.ts
src/lib/avatar/avatar.ts

- Docs have been added/updated:N
Automatically hide the text if an image is rendered.
Fixes #862

fix(avatar): hide text when image is rendered

---

src/dev/pages/dialog/dialog.scss
src/lib/dialog/dialog.scss
src/lib/dialog/forge-dialog.scss

It's common to place a `<forge-scaffold>` as the first child within a `<forge-dialog>`. Safari has a problem with this because the scaffold is set to take up 100% of its height, but the dialog uses a flex layout for the container, which essentially collapses the scaffold down to 0 height.
This change sets `height: auto` by default on a slotted `<forge-scaffold>` element to avoid this problem, which also plays nice with all browsers.

feat(dialog): automatically apply `height: auto` to slotted `<forge-scaffold>`

---

package-lock.json
package.json

This was causing an issue with vscodes prettier plugin. Reverting temporarily until that is fixed.

chore: revert `eslint-config-prettier` version upgrade

---

src/lib/button/_core.scss
src/lib/core/styles/tokens/button/_tokens.scss

Switch to a grid layout instead of flex to allow for the button to control its layout, rather than relying on slotted children for dimensions.
Additionally, now that grid is used, I've set the default block padding to `0` because it was interfering with the static height of the button in terms of content alignment.
This fixes a bug in Safari where the text nodes were collapsing due to the flex layout, and slotted selectors could not apply to text nodes to control the flex item dimensions... Using a grid layout should …

fix(button): use grid layout instead of flex to avoid text nodes collapsing

---

src/lib/app-bar/profile-button/app-bar-profile-button.html

The `<forge-app-bar-profile-button>` component is intended to be the placed in the `end` slot of the `<forge-app-bar>` and therefore its default tooltip placement should reflect that and position itself to the `bottom-end` to avoid potential dynamic position updates from covering other app bar content.

fix(app-bar-profile-button): adjust default tooltip placement

---

src/lib/profile-card/profile-card-core.ts

Will now focus the profile button element before the sign out button if it's visible, given that it's the least destructive action and it is rendered first in the DOM order.

fix(profile-card): focus profile button before sign out button if available

---

src/lib/list/list-item/list-item.scss

Ensures that slotted styles only apply to slotted `<button>` elements in the default slot. This fixes a regression caused by #860 where the slotted styles were inadvertently applying to all slotted buttons with `role="button"` (which happened to include buttons placed within other slots).

fix(list-item): fix regression related to slotted `<button>` width applying to other child elements

---

src/lib/core/styles/tokens/switch/_tokens.scss

Use the `medium` (0.56) color emphasis token for disabled state.
We've received feedback that disabled switches are too washed out. This is similar to a change we made in the past related to improving contrast on text field when disabled by increasing the opacity.
Tested the checkbox and radio, but determined those are fine at their current `medium-low` (0.38) opacity.

fix(switch): improve contrast when disabled

---

src/lib/stepper/stepper/stepper-constants.ts

Fixes compatibility issue with external bundlers that import and type check against Forge.

chore(stepper-constants): fix to set explicit index type for compatibility

---

src/lib/select/select/select.html
src/lib/select/select/select.test.ts

- Does this PR introduce a breaking change? [N
- I have linked any related GitHub issues to be closed when this PR is merged?
Fixes #891
Removes duplicate `label` CSS shadow part, instead just relying on the exported `label` part from the `<forge-field>`.
Additionally, updated the internal `<label>` element to use a `<span>` instead as it was set to `aria-hidden="true"` and using a `<label>` element was not necessary for this component.

fix(select): fix duplicate `label` CSS part

---

package-lock.json
package.json

Removes a console warning from the build/linting command to ensure compatibility with our updated version of typescript.

chore: fix lint warning due to typescript compatibility with legacy shared lint rules package

---

src/lib/avatar/avatar.ts
src/lib/badge/badge.ts
src/lib/card/card.ts
src/lib/key/key-item/index.ts
src/lib/key/key-item/key-item.ts
src/lib/key/key/index.ts
src/lib/key/key/key.ts
src/lib/meter/meter-group/index.ts
src/lib/meter/meter-group/meter-group.ts
src/lib/meter/meter/meter.ts

This is a temporary change applied to all current Lit-based components in the library, and will also apply to all future Lit-based components as well. The plan is to migrate fully to Lit over time, but until we do so, we should expose the custom element tag name on Lit components via a static property so that it can be used with the Forge-based `@customElement` decorator.
This isn't necessarily to support using these decorators interchangeable within Forge (although you should be able to now), but it's to fix a …

fix: enable Lit-based component compatibility with Forge `@customElement` decorator

---

src/lib/dialog/dialog-adapter.ts
src/lib/dialog/dialog-constants.ts
src/lib/dialog/dialog.html
src/lib/dialog/dialog.test.ts

Screen readers were not announcing the accessible label and description for the dialog when opening due to the dynamic nature of how we were handling the internal accessible elements. This change ensures that these accessible elements are always available in the DOM statically to avoid any async DOM updates aside from text content changing.

fix(dialog): update accessible label and description handling for improved ARIA support

---

src/lib/dialog/dialog-constants.ts
src/lib/dialog/dialog-core.ts
src/lib/dialog/dialog.test.ts
src/lib/dialog/dialog.ts

The `forge-dialog-before-close` custom event will now contain an object in its `detail` property that provides the `reason` as to why the dialog is closing. This event will dispatch whenever a light dismiss action occurs (which will provide whether the escape key was pressed or the backdrop was clicked to trigger the light dismiss), or when the dialog is closed via `formmethod="dialog"` submission.
This primarily exposes the ability for developers to handle light dismiss actions differently whether that is triggered via …

feat(dialog): add "reason" for why dialog is about to close to event `detail`

---

src/lib/core/utils/position-utils.ts
src/lib/overlay/base/base-overlay-core.ts
src/lib/overlay/base/base-overlay.ts
src/lib/overlay/base/overlay-aware-core.ts
src/lib/overlay/overlay-adapter.ts
src/lib/overlay/overlay-constants.ts
src/lib/overlay/overlay-core.ts
src/lib/overlay/overlay.test.ts
src/lib/overlay/overlay.ts
src/lib/popover/popover.scss
src/lib/popover/popover.test.ts

- Removed usage of default fallback placements in favor of relying fully on floating-ui's computed best fit positioning strategy
- Adjusted how we handle ensuring popovers stay in view with overflow
- Enable floating-ui's shift middleware by default and adjusted typings for `shift` API on overlay to accept specific string values.
- Allow for `shift` to continue to accept boolean values for backwards compatibility.
- Use `visibility: hidden` for hide state instead of `display: none` per floating-ui docs

fix: updated how overlay positioning is handled when overflowing the viewport bounds

---

src/lib/table/_core.scss

The border was being hidden when using `fixed-headers` because of the `background` style on the `<th>` "covering" the element due to collapsing borders.
This change unsets `border-collapse` (leaving as the default of `separate`) so that the borders are included in the cell dimensions, and instead sets `border-spacing: 0` to collapse the default cell spacing.

fix(table): fixed a bug where the table head cell border could be hidden

---

src/dev/pages/app-bar/app-bar.ejs
src/dev/pages/app-bar/app-bar.html
src/dev/pages/app-bar/app-bar.scss
src/dev/pages/app-bar/app-bar.ts
src/dev/src/partials/header.ejs
src/lib/app-bar/app-bar/_core.scss
src/lib/app-bar/app-bar/app-bar-constants.ts
src/lib/app-bar/app-bar/app-bar-core.ts
src/lib/app-bar/app-bar/app-bar.scss
src/lib/app-bar/app-bar/app-bar.test.ts
src/lib/app-bar/app-bar/app-bar.ts
src/lib/app-bar/forge-app-bar.scss
src/lib/app-bar/help-button/app-bar-help-button.html
src/lib/app-bar/menu-button/app-bar-menu-button.html
src/lib/app-bar/notification-button/app-bar-notification-button.html
src/lib/app-bar/profile-button/app-bar-profile-button.html
src/lib/app-bar/search/app-bar-search.scss
src/lib/button/button-constants.ts
src/lib/button/button.scss
src/lib/core/styles/tokens/app-bar/app-bar/_tokens.scss
src/lib/icon-button/icon-button-constants.ts
src/lib/icon-button/icon-button.scss
src/lib/tabs/tab-bar/tab-bar.scss
src/stories/components/app-bar/AppBar.mdx
src/stories/components/app-bar/AppBar.stories.ts

- Does this PR introduce a breaking change? Potential for visual regression, but has migration steps.
This change adds a new `theme-mode="scoped"` API that allows developers to opt-out of the built-in global theme token overrides that are applied to the `<forge-app-bar>` in favor of two new tokens designed specifically for targeting certain child elements within an app bar:
- `--forge-app-bar-theme-foreground`
- `--forge-app-bar-theme-foreground-muted`
These two new tokens will not apply to any elements by default, but I have also added a new opt-in …

feat(app-bar): remove default auto-theming in favor of scoped CSS variables and theme attribute

---

src/lib/app-bar/app-bar/_core.scss

We only care to ensure that logos fit within the height bounds of the app bar. The width style was incorrectly restricting logos to be square causing issues and requiring devs to override this.
This change just removes the `width` style that is applied to slotted logos. This enables wider images (which is very common, especially in customer branding) where logos are not square.

fix(app-bar): remove default width to allow for wider logos without overriding styles

---

src/lib/dialog/dialog-constants.ts

The `'slide-up' | 'slide-down' | 'slide-left' | 'slide-right'` values on the `DialogAnimationType` type are not used within the dialog component. This change just removes them from the exported type to avoid confusion.
These values were originally intended to be implemented and available during initial implementation, but it was later replaced with the `preset` API (which hardcodes these animations for the sheet variants).
Removed in response question raised in #898

chore(dialog): remove unused slide direction values from `DialogAnimationType`

---

src/lib/core/utils/event-utils.ts
src/lib/list/list-item/list-item-core.ts

Current behavior inspects the composed path for interactive events on a list item (mousedown, click, and keydown) to look for specific elements within the path of elements that event took. Since the composed path contains ALL elements within the bubbling path, it could potentially match against elements we don't care about since it's outside the scope of the specific list item.
This change adds a new utility to capture only composed elements on an event path starting from a specific element. In this case we only care …

fix(list-item): fixed a bug where multiple clicks on the interactive element could occur

---

src/lib/toolbar/_core.scss
src/lib/toolbar/toolbar.scss

- Does this PR introduce a breaking change? Y?
A `min-width` has been added to the center slots of the `toolbar` component.
Fixes #908 
The `inner-center` received a new mix-in to avoid having a justification center added and possibly causing a break with current functionality

fix(toolbar): Apply min-width to grid center slots to allow overflows

---

src/lib/view-switcher/view-switcher.scss
src/lib/view-switcher/view-switcher.ts

Moved the `--forge-view-switcher-height` and `--forge-view-switcher-width` declarations from the view switcher's root element to its host element to fix unexpected behavior. All custom properties have also been documented.

fix(view-switcher): output height and width tokens on host element

---

src/lib/avatar/index.ts
src/lib/badge/index.ts
src/lib/card/index.ts
src/lib/key/key-item/index.ts
src/lib/key/key/index.ts
src/lib/meter/meter-group/index.ts
src/lib/meter/meter/index.ts

Modifying a handful of defineXComponent calls in some component `index.ts` files to use the standard `defineCustomElement` call that `forge-core` offers.

chore: consolidating various defineXComponent calls to use the standard forge-core defineCustomElement call

---

src/dev/pages/overlay/overlay.html
src/lib/overlay/overlay-constants.ts
src/lib/overlay/overlay.test.ts
src/lib/overlay/overlay.ts
src/lib/popover/popover.test.ts

The default state for the overlay `hide` property is now set to `"never"` (instead of `"anchor-hidden"`). This tells the overlay **not** to hide itself when its anchor element is hidden from view via a clipping container (typically a scrollable parent element/containing block).
The reason for this change is due to inconsistencies in detecting clipping ancestors across browsers. This functionality is an implementation detail behind most other popover-based components, and can be enabled if a developer chooses to use the …

fix(overlay): do not hide overlay by default when clipped by ancestors

---

src/lib/list/list-item/list-item.scss
src/lib/list/list/list.scss

As a general best practice in Forge we do not like to set external margins on host elements to ensure the components do not affect layouts with whitespace. Margins are typically something we expect consuming developers to place on the host elements with their own styles.
The list and list item components are unique in that they have some usage patterns for built-in whitespace such as navlist block margin (typically used within dropdown lists), and `indented` where list items have `margin-inline-start` applied to convey …

fix(list): move margins from host to internal container element

---

src/lib/time-picker/time-picker-core.ts
src/test/spec/time-picker/time-picker.spec.ts

Min and max values that wrap around midnight will now show the correct options in the dropdown, and allow for values within the range defined by the min and max values.
Additionally, I also updated the `min` and `max` setters to dispatch the change event if changing the min/max values causes the time value to be removed.

fix(time-picker): allow min and max to wrap around midnight

---

src/lib/menu/menu-core.ts

Previously cascading child menus would only allow either left or right fallback placements. This caused issues on smaller viewports where menus could potentially not fit on either side of the parent menu. This change adds additional fallback placements of bottom and top to try for this scenario in that order. This should allow for more graceful handling of menus on smaller viewports to ensure the user can still access the menu options.
While this change allows a graceful fallback, using cascading menus on mobile …

fix(menu): allow cascading menus to use bottom and top placements if left or right isn't available

---

src/lib/core/styles/tokens/field/_tokens.scss
src/lib/field/_core.scss
src/lib/field/field.ts

- Tests for the changes have been added/updated: [N]
- Docs have been added/updated: [Y]
There's situations, especially when using 3rd party plugins with the text field, that we need to modify the overflow and isolation CSS properties. This change gives us an easy way to do that, but leaves the default values

fix(field): add overflow and isolation token to the inner container element

---

src/lib/date-picker/base/base-date-picker-core.ts
src/lib/date-range-picker/date-range-picker-core.ts

The end date input mask was not being destroyed when setting `masked = false`, this change updates the base class to use a method for destroying the mask so that the date-range-picker can override that and ensure it cleans up the mask on the end input as well.

feat(date-range-picker): fixed a bug where the input mask was not being destroyed on end date input if turning off the mask

---

src/lib/app-bar/profile-button/app-bar-profile-button-adapter.ts
src/stories/components/app-bar/profile/profile.mdx

- I have linked any related GitHub issues to be closed when this PR is merged? Y (Closes #974)
* Updated the tooltip within component to include the avatar text (will use the full name if provided)
* Added a deprecation notice to the docs recommending migration to the new user profile component in the extended library.
This does not account for localization. This component is deprecated and it's recommended to use the extended component which does support localization and further enhancements to this pattern/component will be done in that library.

fix(profile-button): update tooltip text and add deprecation notice in docs

---

src/lib/tooltip/tooltip-adapter.ts
src/lib/tooltip/tooltip-core.ts
src/lib/tooltip/tooltip.test.ts

Tooltips will now open when focusing anchor elements via keyboard (when `:focus-visible`) to improve accessibility compliance.

fix(tooltip): open when focused via keyboard

---

src/lib/table/_core.scss
src/lib/table/table-utils.ts
src/lib/table/table.ts

Fixes #986 
Replaced the native `outline` style on table headers to use the `<forge-focus-indicator>` instead for improved accessibility when it comes to clipped focus indicators, as well as improve consistency with the overall design and interactions.

fix(table): replace outline style with focus indicator for improved accessibility and consistency

---

forge.json
src/dev/pages/select/select.ejs
src/dev/pages/select/select.html
src/dev/pages/select/select.ts
src/lib/list-dropdown/list-dropdown-constants.ts
src/lib/list-dropdown/list-dropdown-utils.ts
src/lib/select/core/base-select-constants.ts
src/lib/select/core/base-select-core.ts
src/lib/select/select/select-constants.ts
src/lib/select/select/select.test.ts
src/lib/select/select/select.ts
src/stories/components/select/Select.mdx
src/stories/components/select/Select.stories.ts

Introduces a new ["Select all" feature](https://forge.tylerdev.io/pr/tyler-technologies-oss:feat/select-all/?path=/docs/components-select--docs#select-all) to the select component when used in `multiple` mode, enabling users to easily select or deselect all options at once. The implementation adds a new static "Select all" option above all other options in the dropdown, and preserves keyboard navigation and event handling.
Closes #93

feat(select): add "Select all" functionality
