tyler-technologies-oss/forge

src/demo/scripts/paginator.js, src/lib/paginator/paginator-foundation.ts, src/test/spec/paginator/paginator.spec.ts
- Tests for the changes have been added: [Y/N] Y
- Docs have been added / updated: [Y/N]
- Does this PR introduce a breaking change? [Y/N] N
- I have linked any related GitHub issues to be closed when this PR is merged? [Y/N] Y
A clear and concise description of the changes, including an breaking changes (if applicable)
Add any other context about the change here.
issue link is found here https://github.com/tyler-technologies-oss/forge/issues/144
=> feat: allow cancellation of pagination

src/lib/inline-message/inline-message.scss
The host element was missing the `display: block` style and it has now been added.
=> fix(inline-message): set host to be a block level element

auto.config.ts, package-lock.json, package.json
Configures Auto to post a Slack message with release notes to the internal #tyler-forge channel when a new release is published.
=> chore: post release notes to slack

src/lib/autocomplete/autocomplete-adapter.ts, src/lib/autocomplete/autocomplete-foundation.ts, src/test/spec/autocomplete/autocomplete.spec.ts, src/tsconfig-test.json
Activates the selected option when opening the dropdown via down arrow key (previously was always activating the first option).
Fixes #161
=> fix(autocomplete): fixed a bug where opening the dropdown via down arrow key would not activate the selected option

src/stories/src/guides/framework-usage.stories.mdx
- Tests for the changes have been added: n/a
Update framework usage guide to describe new Angular usage without `CUSTOM_ELEMENTS_SCHEMA`.
Should be merged after tyler-technologies-oss/forge-angular#13 has merged and been published.
=> chore: update Angular framework usage

src/lib/autocomplete/autocomplete-constants.ts, src/lib/field/field-constants.ts, src/lib/field/field.ts, src/test/spec/chip-field/chip-field.spec.ts, src/test/spec/text-field/text-field.spec.ts
Fixes #194 
The field component (base class for chip field and text field) will now check for the presence of an input/textarea correctly before initializing, rather than just initializing if any child element is present. This resolves an error when referencing the input element within the chip-field.
=> fix(field): fixed incorrect checking for presence of input/textarea

src/lib/color-picker/color-picker-foundation.ts
Added safe guard checks to ensure that DOM-related references aren't used until the element has been connected to the DOM.
Fixes #241
=> fix(color-picker): fixed initialization exceptions when properties were set before connected to DOM

src/lib/table/table-foundation.ts, src/lib/table/table.ts, src/stories/src/components/table/table.mdx, src/test/spec/table/table.spec.ts
Added a new method called `isColumnHidden()` that takes in a column index and returns a boolean indicating whether that column is currently hidden from view or not.
Closes #246
=> feat(table): added new method `isColumnHidden()`

src/dev/pages/chip-field/chip-field.ejs, src/dev/pages/chip-field/chip-field.ts, src/lib/autocomplete/autocomplete-adapter.ts, src/lib/autocomplete/autocomplete-foundation.ts, src/lib/chip-field/chip-field-adapter.ts, src/lib/chip-field/chip-field-foundation.ts
Clicking on the internal input container element will now propagate the `click` event to the slotted `<input>` element.
Fixes #267
=> fix(chip-field): fixed a bug where clicking on the field would not propagate the click event

src/lib/view-switcher/_mixins.scss, src/stories/src/components/view-switcher/view-switcher.mdx
Added a new `--forge-view-switcher-width` CSS custom property (default value is `auto`) to the `<forge-view-switcher>` element.
Closes #277
=> feat(view-switcher): added new `--forge-view-switcher-width` CSS custom property

src/dev/pages/chips/chips.ejs, src/dev/pages/chips/chips.ts, src/lib/chips/chip-set/chip-set-adapter.ts, src/lib/chips/chip-set/chip-set-foundation.ts, src/lib/chips/chip-set/chip-set.ts, src/lib/chips/chip/_mixins.scss, src/lib/chips/chip/chip-adapter.ts, src/lib/chips/chip/chip-constants.ts, src/lib/chips/chip/chip-foundation.ts, src/lib/chips/chip/chip.html, src/lib/chips/chip/chip.ts, src/lib/ripple/forge-ripple.ts, src/stories/src/components/chips/chips.mdx, src/test/spec/chips/chips.spec.ts
The general semantics of the chip template has changed slightly to account for some accessibility problems. This required further changes to support separate button elements and how the ripple is applied.
- Moved button semantics to chip content element to fix nested interactive elements
- Fixed accessibility related to the delete button element
- Improved keyboard navigation
Fixes #184
=> fix(chip): fixed accessibility issues

src/dev/pages/date-picker/date-picker.ejs, src/dev/pages/date-range-picker/date-range-picker.ejs, src/lib/chip-field/chip-field-foundation.ts, src/lib/date-picker/base/base-date-picker-adapter.ts, src/lib/date-picker/base/base-date-picker-foundation.ts, src/lib/date-picker/date-picker-adapter.ts, src/lib/date-picker/date-picker-foundation.ts, src/lib/date-range-picker/date-range-picker-adapter.ts, src/lib/date-range-picker/date-range-picker-foundation.ts, src/lib/field/field-adapter.ts, src/lib/field/field-foundation.ts, src/lib/text-field/text-field-adapter.ts, src/lib/time-picker/time-picker-adapter.ts, src/lib/time-picker/time-picker-foundation.ts, src/stories/src/components/date-picker/date-picker.mdx, src/stories/src/components/date-range-picker/date-range-picker.mdx, src/stories/src/components/time-picker/time-picker.mdx, src/test/spec/date-picker/date-picker.spec.ts, src/test/spec/date-range-picker/date-range-component-delegate.spec.ts, src/test/spec/date-range-picker/date-range-picker.spec.ts, src/test/spec/time-picker/time-picker.spec.ts
- Tests for the changes have been added/updated: [Y]
- Docs have been added/updated: [Y]
- I have linked any related GitHub issues to be closed when this PR is merged? [Y]
time-picker, date-picker, and date-range-picker will now only display masks when they are focused. Also masks will hide on blur when no value is populated.
Closes: https://github.com/tyler-technologies-oss/forge/issues/314
=> fix(masks): time-picker, date-picker, date-range-picker > updates to mask behavior

src/lib/utils/color-utils.ts
- Tests for the changes have been added/updated: [Y/N] Y
- Docs have been added/updated: [Y/N] N
- Does this PR introduce a breaking change? [Y/N] N
- I have linked any related GitHub issues to be closed when this PR is merged? [Y/N] Y
added case insensitivity when getting the color of text
Fixes #335
=> fix(text-to-color): convert text input to uppercase

package-lock.json, package.json
See https://github.com/tyler-technologies-oss/forge-core/pull/11 for more information.
=> feat: bump `@tylertech/forge-core` to `2.3.1` to use constructable stylesheets by default

package-lock.json, package.json
Fixes release issues caused by git 2.43.0 from the `@auto-it/core` package when run in GitHub Actions.
More info here:
https://github.com/intuit/auto/pull/2426
=> chore: upgrade auto to fix release

src/lib/page-state/page-state.ts
=> fix(page-state): include jsdocs

src/lib/button/_button.mixins.scss
- update the hyperlink class to have the underline always present and cursor pointer.
Closes #498
=> feat:  update `forge-hyperlink` CSS class to use `text-decoration: underline`

src/dev/pages/checkbox/checkbox.ejs, src/dev/pages/checkbox/checkbox.html, src/dev/pages/checkbox/checkbox.ts, src/lib/checkbox/_core.scss, src/lib/checkbox/build.json, src/lib/checkbox/checkbox-adapter.ts, src/lib/checkbox/checkbox-constants.ts, src/lib/checkbox/checkbox-foundation.ts, src/lib/checkbox/checkbox.html, src/lib/checkbox/checkbox.scss, src/lib/checkbox/checkbox.test.ts, src/lib/checkbox/checkbox.ts, src/lib/constants.ts, src/lib/core/styles/tokens/checkbox/_tokens.scss
Removed the internal input element and support for slotting an input. The host element itself is now the semantic checkbox. Other changes have been made to use the more current patterns being employed by other form-associated components, such as default ARIA and mixins.
Closes #504
=> chore(checkbox): remove input elements and bring up to date with latest patterns

src/dev/pages/date-picker/date-picker.ts, src/dev/pages/date-range-picker/date-range-picker.ts, src/lib/calendar/calendar-constants.ts, src/lib/core/base/base-adapter.ts, src/lib/date-picker/base/base-date-picker-adapter.ts, src/lib/date-picker/base/base-date-picker-foundation.ts, src/test/spec/date-picker/date-picker.spec.ts
- Tests for the changes have been added/updated: [Y/N] - Y
- Does this PR introduce a breaking change? [Y/N] - N
- I have linked any related GitHub issues to be closed when this PR is merged? [Y/N] - N
Added month change event for date-picker and date-range-picker
- Screenshot of passed tests
=> feat: added month change event for date-picker and date-range-picker

src/stories/blocks/CustomArgTypes.tsx, src/stories/components/accordion/Accordion.mdx, src/stories/components/accordion/Accordion.scss, src/stories/components/accordion/Accordion.stories.ts
=> Next storybook refactor accordion

src/lib/card/card.ts, src/stories/components/card/Card.mdx, src/stories/components/card/Card.scss, src/stories/components/card/Card.stories.ts
=> feat: add card storybook

src/stories/components/skeleton/Skeleton.mdx, src/stories/components/skeleton/Skeleton.stories.ts
=> feat: add skeleton storybook

src/stories/components/inline-message/InlineMessage.mdx, src/stories/components/inline-message/InlineMessage.stories.ts
=> feat: add inline messages to storybook

src/lib/linear-progress/linear-progress.ts, src/stories/components/inline-message/InlineMessage.mdx, src/stories/components/linear-progress/LinearProgress.mdx, src/stories/components/linear-progress/LinearProgress.stories.ts
=> feat: add linear progress storybook

src/lib/open-icon/open-icon.ts, src/stories/components/open-icon/OpenIcon.mdx, src/stories/components/open-icon/OpenIcon.stories.ts
=> feat: add open icon storybook

src/lib/list/list-item/list-item.ts, src/lib/list/list/list.ts, src/stories/components/list/List.mdx, src/stories/components/list/List.stories.ts
=> feat: storybook refactor list

src/lib/button-area/button-area.ts, src/stories/components/button-area/ButtonArea.scss, src/stories/components/button-area/ButtonArea.stories.ts
=> Next storybook refactor button area

src/stories/components/menu/Menu.mdx, src/stories/components/menu/Menu.stories.ts, src/stories/utils.ts
=> feat: add menu to storybook

src/lib/checkbox/checkbox.ts, src/stories/components/checkbox/Checkbox.stories.ts
=> feat: storybook refactor checkbox

src/lib/button-toggle/button-toggle-group/button-toggle-group.ts, src/lib/button-toggle/button-toggle/button-toggle.ts, src/stories/components/button-toggle/ButtonToggle.mdx, src/stories/components/button-toggle/ButtonToggle.stories.ts, src/stories/components/text-field/TextField.stories.ts
Storybook for the button toggle
=> Next storybook refactor button toggle

src/stories/components/profile-card/ProfileCard.mdx, src/stories/components/profile-card/ProfileCard.stories.ts
=> feat: add profile card

src/lib/toolbar/toolbar.ts, src/stories/components/toolbar/Toolbar.mdx, src/stories/components/toolbar/Toolbar.stories.ts
=> Next storybook refactor toolbar

src/stories/components/radio/Radio.mdx, src/stories/components/radio/Radio.stories.ts, src/stories/components/radio/radio-group/RadioGroup.mdx, src/stories/components/radio/radio-group/RadioGroup.stories.ts
=> feat: add radios to storybook

src/stories/components/scaffold/Scaffold.mdx, src/stories/components/scaffold/Scaffold.scss, src/stories/components/scaffold/Scaffold.stories.ts
=> feat: add scaffold

src/stories/components/switch/Switch.mdx, src/stories/components/switch/Switch.stories.ts
=> feat: add switch to storybook

src/lib/time-picker/time-picker.ts, src/stories/components/time-picker/TimePicker.mdx, src/stories/components/time-picker/TimePicker.stories.ts
=> Next storybook refactor time picker

src/stories/components/view-switcher/ViewSwitcher.mdx, src/stories/components/view-switcher/ViewSwitcher.scss, src/stories/components/view-switcher/ViewSwitcher.stories.ts
=> feat: add add view switcher

src/lib/date-range-picker/date-range-picker.ts, src/stories/components/date-range-picker/DateRangePicker.mdx, src/stories/components/date-range-picker/DateRangePicker.stories.ts
=> feat: add date range picker to storybook

src/stories/components/paginator/Paginator.stories.ts
=> chore: add paginator

src/stories/components/page-state/PageState.mdx, src/stories/components/page-state/PageState.stories.ts
=> feat: add page state to storybook

src/lib/color-picker/color-picker.ts, src/stories/components/color-picker/ColorPicker.stories.ts
Storybook for the color-picker
=> feat: storybook refactor color picker

src/lib/date-picker/base/base-date-picker.ts, src/lib/date-picker/date-picker.ts, src/stories/components/date-picker/DatePicker.stories.ts
=> Next storybook refactor date picker

src/lib/autocomplete/autocomplete-adapter.ts, src/lib/autocomplete/autocomplete-foundation.ts, src/lib/core/utils/utils.ts, src/lib/date-picker/date-picker-adapter.ts, src/lib/date-picker/date-picker-constants.ts, src/lib/date-range-picker/date-range-picker-adapter.ts, src/lib/list-dropdown/list-dropdown-constants.ts, src/lib/list-dropdown/list-dropdown-utils.ts, src/lib/list/list-item/list-item-adapter.ts, src/lib/menu/menu-adapter.ts, src/lib/menu/menu-foundation.ts, src/lib/select/core/base-select-adapter.ts, src/lib/select/core/base-select-foundation.ts, src/lib/select/option/option.ts, src/lib/select/select-dropdown/select-dropdown-adapter.ts, src/lib/select/select/select-adapter.ts, src/lib/select/select/select-foundation.ts, src/lib/time-picker/time-picker-adapter.ts, src/lib/time-picker/time-picker-foundation.ts, src/test/spec/date-range-picker/date-range-picker.spec.ts, src/test/spec/list-dropdown/list-dropdown.spec.ts, src/test/spec/select/select-dropdown.spec.ts, src/test/spec/select/select.spec.ts
- Tests for the changes have been added/updated: [Y]
- Docs have been added/updated: [N]
Fixed various issues with the popup discovered with ARC toolkit, mainly around how aria-controls is handled on dynamic popups
=> fix: fixed accessibility issues with popups

src/stories/components/table/Table.stories.ts
- Docs have been added/updated: N/A
https://github.com/tyler-technologies-oss/forge/issues/651
Adds `id` to table data and sets the `selectKey` to `id` to ensure rowSelect functionality in storybook.
=> refactor: add unique identifier to table data items

src/lib/app-bar/profile-button/app-bar-profile-button.ts, src/lib/autocomplete/autocomplete.ts, src/lib/banner/banner.ts, src/lib/chips/chip/chip.ts, src/lib/icon-button/icon-button.ts, src/lib/split-view/split-view-panel/split-view-panel.ts
Updates JSDoc for custom elements manifest to fix event types that are either missing or incorrect.
=> docs: fix event types

src/lib/select/select/select.ts
- Tests for the changes have been added/updated: n/a
Show a list of all available slots in the docs
Resolves #653
=> docs(select): update incorrect slot docs

src/dev/pages/skip-link/skip-link.ejs, src/lib/core/styles/tokens/skip-link/_tokens.scss, src/lib/skip-link/_core.scss, src/lib/skip-link/skip-link-constants.ts, src/lib/skip-link/skip-link.scss, src/lib/skip-link/skip-link.test.ts, src/lib/skip-link/skip-link.ts, src/stories/components/skip-link/SkipLink.mdx, src/stories/components/skip-link/SkipLink.stories.ts
Changed the skip link to have an inset on all sides and use a uniform border radius. An `inline` property has been added to enable rendering a skip link within a container.
=> feat(skip-link): add inline variant and style tweaks

package-lock.json, package.json, src/lib/core/mask/intermediate-time-parser.ts, src/lib/split-button/split-button-core.ts
Upgrade to the latest TylerTech eslint rules package to fix dependency compatibility warnings/errors.
Upgrading to eslint v9 will occur in the near future.
=> chore: updated `@tylertech-eslint/eslint-plugin` to latest

src/lib/list/list/_core.scss, src/lib/list/list/list.scss
Moves the internal grid layout where the spacing token is used on the `gap` property to the `inner` class.
=> fix(list): fix spacing token

package-lock.json, package.json, src/stories/components/app-bar/AppBar.mdx, src/stories/components/app-bar/profile/profile.stories.ts, src/stories/components/badge/Badge.mdx, src/stories/design-tokens/Shape.mdx, src/stories/getting-started/Installation.mdx
Bump to latest Forge CLI version to use new build configuration, and clean up various docs typos in Storybook.
=> feat: bump to latest Forge CLI

src/stories/components/dialog/Dialog.mdx
DialogConfig is not used so removed
=> docs: removed DialogConfig

src/lib/date-range-picker/date-range-picker-adapter.ts
Ensures that only a single separator element is added to the DOM.
=> fix(date-range-picker): fixed a bug where multiple input separators could be added

src/lib/text-field/text-field-adapter.ts
Ensures that only a single separator element exists in the DOM.
Fixes #695
=> fix(text-field): fixed a bug where multiple input separators could be added

src/lib/inline-message/_core.scss
Aligns the slotted content in the center along the vertical axis, while also ensuring that any slotted icons stay aligned to the start in case of multiple lines/larger content.
=> fix(inline-message): fix content alignment

src/lib/toolbar/toolbar.html
Fixed "after-section-end" part name.
=> fix(toolbar): fixed "after-section-end" part name

src/lib/core/styles/tokens/toolbar/_tokens.scss, src/lib/toolbar/_core.scss, src/lib/toolbar/toolbar.ts
This adds a `--forge-toolbar-columns` token to match the app bar token from #768
=> feat(toolbar): make columns customizable

src/stories/components/table/Table.stories.ts
Small change to ensure the `forge-table-select-all` event is logged in the Storybook "Actions" panel.
=> docs(table): add action logging for `forge-table-select-all` event

src/lib/dialog/dialog-core.ts, src/lib/dialog/dialog.ts
Adds the `mode` property on `<forge-dialog>` to be globally configurable.
=> feat(dialog): add `mode` to global configuration

src/lib/expansion-panel/_core.scss
A rendering artifact was reported when expanding an expansion panel in Chrome. This was determined to be caused by the CSS animation running on the CPU causing problems due to the heavy layout calculations. Forcing the animation to run on the GPU fixes this problem.
=> fix(expansion-panel): fixed a rendering artifact caused by CSS animation

src/lib/dialog/dialog-core.ts
Use a capturing listener to ensure the dialog can respond and potentially cancel the event as soon as possible.
=> fix(dialog): use capturing keydown listener

src/lib/avatar/avatar-constants.ts, src/lib/avatar/avatar.ts, src/lib/card/card-constants.ts, src/lib/card/card.html, src/lib/card/card.scss, src/lib/card/card.test.ts, src/lib/card/card.ts, src/lib/card/index.ts
Converting the `<forge-card>` component to be implemented with Lit.
=> feat(card): refactor to use Lit

src/lib/tabs/tab-bar/tab-bar-core.ts
Rather than storing a reference to the `<forge-tab>` element instances within the `<forge-tab-bar>`, this change swaps that out for just querying the DOM for the current child tabs at any given time when needed. This avoids any race conditions and ensures we're aways acting upon the latest DOM state, while also avoiding capturing element references which can cause memory leaks.
This was caused by the `slotchange` listener getting added _after_ the component initializes and the DOM is rendered, which meant the internal …
=> fix(tab-bar): fixed a bug where child tabs were not synchronizing with the active tab state
